import React,{useEffect,useState} from 'react';
import {Alert,Button,Checkbox,FormControlLabel,MenuItem,TextField} from '@mui/material';
import {actions,activityTemplate,normalizeActivity,activityView,activityCoverage} from './activity/engine.mjs';
import {inspectSchwabActivity} from './activity/schwab.mjs';
const download=(name,value)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const blankRow=()=>({rowRef:'',brokerId:null,date:null,symbol:null,exchange:null,action:'buy',quantity:null,cashAmount:null,currency:null,note:''});
const blankDocument=()=>({...activityTemplate(),sourceAccount:'',reference:'',reason:'',coverage:{start:'',end:'',status:'partial',noActivity:false},rows:[]});
export default function Activity({store,initialFile,onFileConsumed}:{store:any,initialFile?:any,onFileConsumed?:()=>void}){
  const [saved,setSaved]=useState<any>(null),[doc,setDoc]=useState<any>(blankDocument),[row,setRow]=useState<any>(blankRow),[account,setAccount]=useState(''),[file,setFile]=useState<any>(null);
  const [preview,setPreview]=useState<any>(null),[decisions,setDecisions]=useState<any>({}),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [rangeStart,setRangeStart]=useState(''),[rangeEnd,setRangeEnd]=useState(''),[coverage,setCoverage]=useState<any>(null),[withdrawReason,setWithdrawReason]=useState('');
  const [backup,setBackup]=useState<any>(null),[mapping,setMapping]=useState<any>({}),[restoreReason,setRestoreReason]=useState('');
  const [analysis,setAnalysis]=useState<any>(null);
  const [csvCurrency,setCsvCurrency]=useState(''),[tradeDatesConfirmed,setTradeDatesConfirmed]=useState(false);
  useEffect(()=>{if(!initialFile)return;try{const csv=inspectSchwabActivity(initialFile.text);invalidate();setDoc({...blankDocument(),reference:initialFile.name,reason:'Import Schwab transaction export',coverage:{start:csv.start,end:csv.end,status:'partial',noActivity:false},rows:csv.rows});setFile({...initialFile,csv:true});setCsvCurrency('');setTradeDatesConfirmed(false);onFileConsumed?.();}catch(e:any){setError(e.message);}},[initialFile]);
  const isCsv=!!file?.csv;
  useEffect(()=>{let alive=true;store.activity({action:'read'}).then(v=>{if(alive)setSaved(v);}).catch(e=>{if(alive)setError(e.message);});store.analysis({action:'read'}).then(v=>{if(alive)setAnalysis(v);}).catch(()=>{});return()=>{alive=false;};},[store]);
  function invalidate(){setPreview(null);setReviewed(false);setDecisions({});setMessage('');}
  function edit(next){setDoc(next);if(!isCsv)setFile(null);invalidate();}
  async function run(action){setBusy(true);setError('');setMessage('');try{await action();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  const view=saved?activityView(saved.state):null;
  async function prepare(){setReviewed(false);const source=isCsv?{name:file.name,text:file.text,review:{format:'schwab-transactions-csv',version:1,sourceAccount:doc.sourceAccount,reference:doc.reference,reason:doc.reason,coverage:doc.coverage,currency:csvCurrency,tradeDatesConfirmed}}:file??{name:'manual-activity.json',text:JSON.stringify(doc,null,2)};const result=await store.activity({action:'prepare',accountId:account,baseRevision:saved.revision,source,decisions});if(result.duplicate){setPreview(null);setMessage('This normalized source is already accepted in this account. Nothing was duplicated.');}else setPreview(result.preview);}
  function addRow(){let ref=row.rowRef.trim();if(!ref){let n=1;while(doc.rows.some(r=>r.rowRef===`row-${n}`))n++;ref=`row-${n}`;}edit({...doc,rows:[...doc.rows,{...row,rowRef:ref}],coverage:{...doc.coverage,noActivity:false}});setRow(blankRow());}
  return <>
    <Alert severity="info">Record supplied activity separately from holdings. These records do not change positions, basis or lots. Collection coverage is your reviewed declaration, not independent verification or wash-sale clearance.</Alert>
    {error&&<Alert severity="error" sx={{mt:2}}>{error}</Alert>}{message&&<Alert severity="success" sx={{mt:2}}>{message}</Alert>}
    {!saved?<Button onClick={()=>run(async()=>setSaved(await store.activity({action:'read'})))}>Reload activity</Button>:<>
      <section className="card"><h2>Activity source</h2><p>Choose a Schwab transactions CSV, use a versioned manual JSON file, or enter rows below. One source covers one account.</p>
        <Button component="label" disabled={busy}>Choose Schwab transactions CSV<input hidden type="file" accept=".csv" aria-label="Schwab transactions CSV" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)run(async()=>{invalidate();setFile(null);setDoc(blankDocument());setCsvCurrency('');setTradeDatesConfirmed(false);if(f.size>262144)throw new Error('Limit each activity source to 256 KB.');const text=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await f.arrayBuffer()),csv=inspectSchwabActivity(text);setDoc({...blankDocument(),reference:f.name,reason:'Import Schwab transaction export',coverage:{start:csv.start,end:csv.end,status:'partial',noActivity:false},rows:csv.rows});setFile({name:f.name,text,csv:true});});}}/></Button>
        <Button disabled={busy} onClick={()=>download('tlh-manual-activity-template.json',activityTemplate())}>Download activity template</Button><Button component="label" disabled={busy}>Choose activity JSON<input hidden type="file" accept=".json" aria-label="Activity source JSON" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)run(async()=>{invalidate();setFile(null);if(f.size>262144)throw new Error('Limit each activity source to 256 KB.');const text=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await f.arrayBuffer()),parsed=normalizeActivity(JSON.parse(text.replace(/^\uFEFF/,'')));setDoc(parsed);setFile({name:f.name,text});});}}/></Button>
        {file&&<p>Original file: {file.name}. {isCsv?'CSV rows and original text stay unchanged; account and coverage declarations are stored alongside them.':'Editing the form creates a new manual source; the uploaded original is used only while this label remains visible.'}</p>}
        {isCsv&&<><Alert severity="warning">The suggested dates are the earliest and latest rows, not an export coverage period. Keep partial coverage unless you verified all account activity for your chosen range. This export has no account ID, currency code or broker transaction IDs. Verify the source account and date meaning against Schwab. Unrecognized actions remain unclassified.</Alert><TextField disabled={busy} select label="CSV amount currency" value={csvCurrency} sx={{mt:2,minWidth:260}} onChange={e=>{setCsvCurrency(e.target.value);invalidate();}}><MenuItem value="">Confirm currency</MenuItem><MenuItem value="USD">USD — confirmed from my source</MenuItem></TextField><FormControlLabel control={<Checkbox disabled={busy} checked={tradeDatesConfirmed} onChange={e=>{setTradeDatesConfirmed(e.target.checked);invalidate();}}/>} label="I verified that the CSV Date column reports trade dates."/><Button disabled={busy} onClick={()=>{setFile(null);setDoc(blankDocument());invalidate();}}>Clear CSV / enter manually</Button></>}
        <details><summary>View staged source</summary><pre style={{maxHeight:300,overflow:'auto',whiteSpace:'pre-wrap'}}>{file?.text??JSON.stringify(doc,null,2)}</pre></details>
        <div className="form-grid" style={{marginTop:16}}><TextField disabled={busy} select label="Activity account" value={account} onChange={e=>{setAccount(e.target.value);invalidate();}}><MenuItem value="">Choose account</MenuItem>{saved.accounts.map(a=><MenuItem key={a.id} value={a.id}>{a.portfolioName} / {a.label}</MenuItem>)}</TextField>
          {['sourceAccount','reference','reason'].map((key,i)=><TextField disabled={busy} key={key} label={['Source account label','Activity source reference','Activity entry reason'][i]} value={doc[key]} onChange={e=>edit({...doc,[key]:e.target.value})}/>)}
          <TextField disabled={busy} type="date" label="Source range start" value={doc.coverage.start} slotProps={{inputLabel:{shrink:true}}} onChange={e=>edit({...doc,coverage:{...doc.coverage,start:e.target.value}})}/><TextField disabled={busy} type="date" label="Source range end" value={doc.coverage.end} slotProps={{inputLabel:{shrink:true}}} onChange={e=>edit({...doc,coverage:{...doc.coverage,end:e.target.value}})}/>
          <TextField disabled={busy} select label="Activity collection coverage" value={doc.coverage.status} onChange={e=>edit({...doc,coverage:{...doc.coverage,status:e.target.value,noActivity:false}})}><MenuItem value="partial">Partial / selected activity</MenuItem><MenuItem value="complete">All account activity in this range — my declaration</MenuItem></TextField>
        </div><FormControlLabel control={<Checkbox disabled={busy||doc.rows.length>0||doc.coverage.status!=='complete'} checked={doc.coverage.noActivity} onChange={e=>edit({...doc,coverage:{...doc.coverage,noActivity:e.target.checked}})}/>} label="I checked the source: there was no account activity in this entire range."/>
      </section>
      <section className="card"><h2>{isCsv?'CSV activity rows':'Enter activity rows'}</h2><p>Blank values stay unknown. Cash amount is the signed amount as reported, not lot basis. Use adjustment/other with a note when an event cannot be classified.</p>{!isCsv&&<><div className="form-grid">
        <TextField disabled={busy} select label="Activity action" value={row.action} onChange={e=>setRow({...row,action:e.target.value})}>{actions.map(a=><MenuItem key={a} value={a}>{a.replaceAll('_',' ')}</MenuItem>)}</TextField>
        <TextField disabled={busy} type="date" label="Activity trade date" value={row.date??''} slotProps={{inputLabel:{shrink:true}}} onChange={e=>setRow({...row,date:e.target.value||null})}/>
        {['symbol','exchange','quantity','cashAmount','currency','brokerId','rowRef','note'].map((key,i)=><TextField disabled={busy} key={key} label={['Activity symbol','Activity exchange (optional)','Activity quantity','Reported cash amount','Activity currency','Broker transaction ID (optional)','Source row reference (optional)','Activity row note'][i]} value={row[key]??''} onChange={e=>setRow({...row,[key]:['rowRef','note'].includes(key)?e.target.value:(['symbol','exchange','currency'].includes(key)?e.target.value.toUpperCase():e.target.value)||null})}/>)}
        </div><Button disabled={busy||doc.rows.length>=500} onClick={addRow}>Add activity row</Button></>}
        <div className="table-wrap"><table aria-label="Draft activity rows"><thead><tr><th>Source row</th><th>Date / symbol</th><th>Action</th><th>Quantity / cash</th><th>Broker ID</th><th></th></tr></thead><tbody>{doc.rows.map((r,i)=><tr key={i}><td>{r.rowRef}</td><td>{r.date??'Unknown'} / {r.symbol??'Unknown'}</td><td>{r.action}</td><td>{r.quantity??'Unknown'} / {r.cashAmount??'Unknown'} {isCsv?csvCurrency:(r.currency??'')}</td><td>{r.brokerId??'None'}</td><td><Button disabled={busy||isCsv} aria-label={`Remove activity row ${i+1}`} onClick={()=>edit({...doc,rows:doc.rows.filter((_,index)=>index!==i)})}>Remove</Button></td></tr>)}</tbody></table></div>
        <Button disabled={busy||!account||(isCsv&&(!csvCurrency||!tradeDatesConfirmed))} variant="contained" onClick={()=>run(prepare)}>Preview activity</Button>
      </section>
      {preview&&<section className="card"><h2>Review activity {preview.kind??'source'}</h2>
        {preview.document&&<><p>{preview.accountLabel??saved.accounts.find(a=>a.id===account)?.label} · {preview.document.reference} · {preview.document.coverage.start} through {preview.document.coverage.end}, inclusive · {preview.document.coverage.status} collection.</p><p>{preview.newRows} new records; {preview.duplicateRows} duplicate rows excluded. Identical-looking rows within a source retain their multiplicity.</p>
          <div className="table-wrap"><table aria-label="Activity review"><thead><tr><th>Row</th><th>Reported activity</th><th>Result</th><th>Overlap decision</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.row.rowRef}><td>{r.row.rowRef}</td><td>{r.row.date??'Unknown date'} · {r.row.symbol??'Unknown security'} · {r.row.action} · {r.row.quantity??'Unknown quantity'}<small>Cash: {r.row.cashAmount??'Unknown'} {r.row.currency??''}</small><small>{r.row.note}</small></td><td>{r.status}</td><td>{['ambiguous','keep','duplicate'].includes(r.status)&&<TextField disabled={busy} select label={`Overlap ${r.row.rowRef}`} value={decisions[r.row.rowRef]??''} sx={{minWidth:260}} onChange={e=>{setDecisions({...decisions,[r.row.rowRef]:e.target.value});setPreview({...preview,preparedId:null});setReviewed(false);}}><MenuItem value="">Review matching evidence</MenuItem><MenuItem value="keep">Keep as a separate reported transaction</MenuItem>{r.matches.map(m=><MenuItem key={m.id} value={m.id}>Duplicate of {m.rowRef} · {m.id}</MenuItem>)}</TextField>}{r.status==='conflicting-id'&&'This broker ID has different values. Resolve the source discrepancy; withdraw and replace incorrect evidence if needed.'}</td></tr>)}</tbody></table></div>
          {!preview.preparedId&&<Button disabled={busy} onClick={()=>run(prepare)}>Update activity review</Button>}</>}
        {preview.kind==='withdraw'&&<p>Withdraw {preview.source}: {preview.removedRows} active rows removed from the current view; {preview.suspendedSources} dependent sources suspended.</p>}
        {preview.kind==='restore'&&<><p>{preview.restoredEvents} historical events will be restored.</p>{preview.sourceAccounts.map(a=><p key={a.id}>{a.label} → {saved.accounts.find(t=>t.id===preview.mapping[a.id])?.label}</p>)}</>}
        {(preview.warnings??[]).map((w,i)=><Alert key={i} severity="warning" sx={{my:1}}>{w}</Alert>)}
        <FormControlLabel control={<Checkbox disabled={busy||!preview.preparedId} checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>} label="I reviewed the account, original source, overlap choices and collection coverage."/>
        <Button disabled={busy||!preview.preparedId||!reviewed} variant="contained" onClick={()=>run(async()=>{const result=await store.activity({action:'accept',preparedId:preview.preparedId,reviewed});setSaved(result.saved);setCoverage(null);setPreview(null);setReviewed(false);setDecisions({});setMessage(`Activity saved at revision ${result.receipt.revision}. Holdings and lot evidence are unchanged.`);})}>Accept activity review</Button>
      </section>}
      <section className="card"><h2>History coverage in supplied records</h2><p>Query any inclusive date range. Only complete collection declarations with usable classified rows contribute covered dates. Unknown or unclassified overlapping records still flag uncertainty. This does not establish household completeness or wash-sale clearance.</p>
        <div className="table-tools"><TextField type="date" label="Coverage check start" value={rangeStart} slotProps={{inputLabel:{shrink:true}}} onChange={e=>{setRangeStart(e.target.value);setCoverage(null);}}/><TextField type="date" label="Coverage check end" value={rangeEnd} slotProps={{inputLabel:{shrink:true}}} onChange={e=>{setRangeEnd(e.target.value);setCoverage(null);}}/><Button onClick={()=>run(async()=>setCoverage(activityCoverage(saved.state,saved.accounts,rangeStart,rangeEnd)))}>Check supplied coverage</Button></div>
        {analysis&&<p>Household declaration: {analysis.input?.household?.replaceAll('_',' ')??'not reviewed'}. All accounts appear below, including omitted/unreviewed accounts.</p>}
        {coverage&&<div className="table-wrap"><table aria-label="Activity coverage"><thead><tr><th>Account / planned scope</th><th>Result</th><th>Uncovered dates</th><th>Sources</th></tr></thead><tbody>{coverage.map(c=><tr key={c.accountId}><td>{c.label}<small>{analysis?.input?.accounts.find(a=>a.accountId===c.accountId)?.scope??'unreviewed'}</small></td><td>{c.status.replaceAll('_',' ')}</td><td>{c.gaps.map(g=>`${g.start} through ${g.end}`).join('; ')||'No gaps in supplied ranges'}</td><td>{c.sourceCount}</td></tr>)}</tbody></table></div>}
      </section>
      <section className="card"><h2>Accepted activity and sources</h2><p>{view?.transactions.length} active records · {view?.suspended.length} suspended sources · activity revision {saved.revision}. Identical-looking lots are not merged with this ledger. Disposals are not matched to particular lots.</p>
        <TextField fullWidth label="Reason for withdrawing an activity source" value={withdrawReason} onChange={e=>{setWithdrawReason(e.target.value);setPreview(null);setReviewed(false);}}/>
        {view?.batches.map(b=><details key={b.id}><summary>{saved.accounts.find(a=>a.id===b.accountId)?.label} · {b.document.reference} · {view.withdrawn.has(b.id)?'withdrawn':view.suspended.includes(b)?'suspended':'active'} · {b.transactions.length} accepted rows</summary><p>Source acceptance: {b.at} · source actor {b.actor} · {b.document.reason}</p><p>{b.document.coverage.start} through {b.document.coverage.end} · {b.document.coverage.status} collection</p><pre style={{maxHeight:300,overflow:'auto',whiteSpace:'pre-wrap'}}>{b.source.text}</pre>
          <div className="table-wrap"><table aria-label={`Accepted activity ${b.id}`}><thead><tr><th>Row</th><th>Date</th><th>Symbol / exchange</th><th>Action</th><th>Quantity</th><th>Cash amount</th><th>Broker ID</th></tr></thead><tbody>{b.transactions.map(t=><tr key={t.id}><td>{t.rowRef}</td><td>{t.date??'Unknown'}</td><td>{t.symbol??'Unknown'} / {t.exchange??'Unknown'}</td><td>{t.action}</td><td>{t.quantity??'Unknown'}</td><td>{t.cashAmount??'Unknown'} {t.currency??''}</td><td>{t.brokerId??'None'}</td></tr>)}</tbody></table></div>
          <Button disabled={busy||view.withdrawn.has(b.id)} onClick={()=>run(async()=>{setReviewed(false);setPreview((await store.activity({action:'prepare-withdraw',baseRevision:saved.revision,batchId:b.id,reason:withdrawReason})).preview);})}>Preview withdrawal</Button>
        </details>)}
        <Button disabled={busy} onClick={()=>run(async()=>{setSaved(await store.activity({action:'read'}));setAnalysis(await store.analysis({action:'read'}));invalidate();setCoverage(null);})}>Reload saved activity</Button>
      </section>
      <section className="card"><h2>Activity backup and restore</h2><p>This separate backup preserves original activity sources, overlap decisions, accepted rows and withdrawals. Restore maps accounts explicitly; destination accounts must have no activity history.</p><Button disabled={busy||!view?.batches.length} onClick={()=>run(async()=>download('tlh-activity-backup.json',(await store.activity({action:'export'})).backup))}>Export activity backup</Button>
        <Button component="label" disabled={busy}>Choose activity backup<input hidden type="file" accept=".json" aria-label="Activity backup JSON" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)run(async()=>{setBackup(null);setMapping({});invalidate();if(f.size>8*1024*1024)throw new Error('Limit activity backups to 8 MB.');const b=JSON.parse(new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await f.arrayBuffer()).replace(/^\uFEFF/,''));if(b.format!=='tlh-activity-backup'||b.version!==1||!Array.isArray(b.accounts))throw new Error('Choose a version 1 activity backup.');setBackup(b);});}}/></Button>
        {backup&&<>{backup.accounts.map(a=><div key={a.id} className="file"><span>{a.label}</span><TextField disabled={busy} select label={`Activity destination ${a.label}`} value={mapping[a.id]??''} sx={{minWidth:240}} onChange={e=>{setMapping({...mapping,[a.id]:e.target.value});setPreview(null);setReviewed(false);}}><MenuItem value="">Choose account</MenuItem>{saved.accounts.filter(t=>t.type===a.type).map(t=><MenuItem key={t.id} value={t.id}>{t.portfolioName} / {t.label}</MenuItem>)}</TextField></div>)}<TextField fullWidth label="Activity restore reason" value={restoreReason} onChange={e=>{setRestoreReason(e.target.value);setPreview(null);setReviewed(false);}}/><Button disabled={busy||backup.accounts.some(a=>!mapping[a.id])} onClick={()=>run(async()=>{setReviewed(false);setPreview((await store.activity({action:'prepare-restore',baseRevision:saved.revision,backup,mapping,reason:restoreReason})).preview);})}>Preview activity restore</Button></>}
        <details><summary>Acceptance audit</summary>{saved.audit.map(a=><p key={a.id}>Revision {a.revision} · {a.kind} · {a.at} · actor {a.user_id} · {a.reason}</p>)}</details>
      </section>
    </>}
  </>;
}
