import React,{useEffect,useState} from 'react';
import {Alert,Button,Checkbox,FormControlLabel,TextField} from '@mui/material';
export default function AlertInbox({store,onOpen}:any){
 const [data,setData]=useState<any>(null),[preferences,setPreferences]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[all,setAll]=useState(false),[page,setPage]=useState(0);
 async function load(){const d=await store.replacements({action:'alerts-read'});setData(d);setPreferences(d.preferences);}
 async function run(fn){setBusy(true);setError('');setMessage('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{run(load);},[store]);
 async function scan(){await store.replacements({action:'alerts-scan'});await load();setMessage('Alert check completed using saved evidence. No market-data request was made.');}
 const now=Date.now(),rows=(data?.alerts??[]).filter(a=>all||a.active&&!a.acknowledged&&(!a.snoozed_until||Date.parse(a.snoozed_until)<=now)),current=Math.min(page,Math.max(0,Math.ceil(rows.length/25)-1)),last=data?.scans[0];
 return <section className="card"><h1>Alerts</h1><p>Check saved evidence for potential losses, data-quality issues and sale reviews needing attention. These are daily-price and evidence checks, not live market alerts.</p><Alert severity="info">Enable daily checks below to check saved evidence while the local worker is running, even with the browser closed. Missed checks run after the worker restarts. Email delivery is not enabled.</Alert>{error&&<Alert severity="error">{error} Previous alerts are retained; no successful check is implied.</Alert>}{message&&<Alert severity="success">{message}</Alert>}
 {data&&<div className="setup-drawer"><Alert severity={data.worker?.last_seen&&Date.parse(data.now)-Date.parse(data.worker.last_seen)<180000?'success':'warning'}>{data.worker?.last_seen&&Date.parse(data.now)-Date.parse(data.worker.last_seen)<180000?'Local alert worker recently checked in.':'Local alert worker has no recent check-in. Automatic checks may be delayed.'}{data.worker?.last_seen&&` Last check-in: ${new Date(data.worker.last_seen).toLocaleString()}.`} Status is as of the last inbox reload.</Alert><FormControlLabel control={<Checkbox checked={data.schedule?.enabled??false} disabled={busy} onChange={e=>{const enabled=e.target.checked;run(async()=>{await store.replacements({action:'alerts-schedule',enabled,revision:data.schedule?.revision??0});await load();});}}/>} label="Automatic daily checks"/>{data.schedule?.enabled&&<p>Next check due: {new Date(data.schedule.next_run).toLocaleString()}. Runs within a minute while the worker is available. Enabling starts an immediate check, then checks run every 24 hours and after accepted evidence or saved price changes.</p>}{data.schedule?.last_success&&<p>Last automatic success: {new Date(data.schedule.last_success).toLocaleString()}</p>}{data.schedule?.last_error&&<Alert severity="warning">{data.schedule.last_error}</Alert>}<p>Reload inbox to see background results. Turning checks off may allow an already running check to finish.</p></div>}
 <div className="table-tools"><Button variant="contained" disabled={busy} onClick={()=>run(scan)}>Check alerts now</Button><Button disabled={busy} onClick={()=>run(load)}>Reload inbox</Button><FormControlLabel control={<Checkbox checked={all} onChange={e=>{setAll(e.target.checked);setPage(0);}}/>} label="Include acknowledged, snoozed and inactive alerts"/></div>
 {busy&&<p role="status">Working on alerts…</p>}{last?<p>Last successful check: {new Date(last.at).toLocaleString()} · {last.conditions} conditions · holdings revision {last.holdings_revision} · activity revision {last.activity_revision}.</p>:<p>No checks have run yet. Choose categories below, then check alerts.</p>}
 {last&&last.evaluated.opportunity===false&&<Alert severity="warning">Opportunity checks were skipped because prices need updating. Older opportunity alerts remain historical evidence until a fresh check; open Valuation to update daily prices.</Alert>}
 {preferences&&<details className="setup-drawer"><summary>Alert preferences</summary><p>Potential-loss alerts use all taxable USD accounts and the sum of losing lots per holding. Saved analysis exclusions and tax rates are not applied.</p>{[['opportunities','Potential loss opportunities'],['dataQuality','Prices and holding evidence'],['tracking','Post-sale reviews and window milestones']].map(([key,label])=><FormControlLabel key={key} control={<Checkbox checked={preferences[key]} disabled={busy} onChange={e=>setPreferences(p=>({...p,[key]:e.target.checked}))}/>} label={label}/>)}<TextField label="Minimum potential loss per holding (USD)" value={preferences.minLoss} disabled={busy} onChange={e=>setPreferences(p=>({...p,minLoss:e.target.value}))}/><p>Default: $100. Acknowledged opportunity alerts stay quiet while the same holding remains above the threshold. A newly detected condition or changed sale evidence needs review again.</p><Button disabled={busy} onClick={()=>run(async()=>{await store.replacements({action:'alerts-preferences',preferences,revision:data.revision});await scan();})}>Save preferences and check</Button></details>}
 {!busy&&data&&!rows.length&&<p>No alerts in this view. Check the last scan and data-quality status before drawing conclusions.</p>}
 {rows.slice(current*25,(current+1)*25).map(a=><article className="card" key={a.id}><h2>{a.payload.title}</h2><p>{a.payload.message}</p><p>{!a.active?'Not detected by the latest applicable check':a.snoozed_until&&Date.parse(a.snoozed_until)>now?`Snoozed until ${new Date(a.snoozed_until).toLocaleString()}`:a.acknowledged?'Acknowledged':'Needs attention'} · last seen {new Date(a.last_seen).toLocaleString()}</p><Button onClick={()=>onOpen(a.payload.target)}>Open evidence</Button>{a.active&&<><Button disabled={busy||a.acknowledged} onClick={()=>run(async()=>{await store.replacements({action:'alerts-action',id:a.id,version:a.version,choice:'acknowledge'});await load();})}>Acknowledge</Button><Button disabled={busy} onClick={()=>run(async()=>{await store.replacements({action:'alerts-action',id:a.id,version:a.version,choice:'snooze'});await load();})}>Snooze 24 hours</Button>{(a.acknowledged||a.snoozed_until)&&<Button disabled={busy} onClick={()=>run(async()=>{await store.replacements({action:'alerts-action',id:a.id,version:a.version,choice:'reopen'});await load();})}>Mark unread</Button>}</>}<details><summary>Evidence at last check</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(a.payload.evidence,null,2)}</pre></details></article>)}
 <Button disabled={!current} onClick={()=>setPage(current-1)}>Previous alerts</Button><span>Page {current+1} of {Math.max(1,Math.ceil(rows.length/25))}</span><Button disabled={(current+1)*25>=rows.length} onClick={()=>setPage(current+1)}>Next alerts</Button>
 <details><summary>Recent successful checks</summary>{data?.scans.map(s=><p key={s.id}>{new Date(s.at).toLocaleString()} · {s.conditions} conditions · opportunity checks {s.evaluated.opportunity?'evaluated':'skipped — stale prices'}</p>)}</details></section>;
}
