import React,{useEffect,useMemo,useState} from 'react';
import {Alert,Button,Checkbox,FormControlLabel,MenuItem,TextField} from '@mui/material';
import {correctionFields,correctionView,targetKey} from './import/corrections.mjs';

const fieldLabel=f=>f==='confirmedCurrency'?'Confirmed currency':f.replaceAll('_',' ');
const label=t=>`${t.section==='lot'?`Lot row ${t.row+1}`:t.section==='lots'?'Lot scope':t.section} · ${fieldLabel(t.field)}`;
const display=v=>v===null||v===undefined?'Unknown':typeof v==='object'?'effective_date' in v?(v.effective_at??v.effective_date??'Unknown'):JSON.stringify(v):String(v);
export default function Corrections({state,store,onChanged,initial}:{state:any,store:any,onChanged:(s:any)=>void,initial:any}){
  const [account,setAccount]=useState(initial?.accountId??''),[symbol,setSymbol]=useState(initial?.symbol??'');
  const [section,setSection]=useState('position'),[field,setField]=useState('total_basis'),[row,setRow]=useState(0);
  const [value,setValue]=useState(''),[unknown,setUnknown]=useState(false),[reason,setReason]=useState(''),[kind,setKind]=useState('set');
  const [preview,setPreview]=useState<any>(null),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const view=useMemo(()=>correctionView(state),[state]);
  const target={section,field,...(section==='lot'?{row}:{})};
  const current=view.correctionStates.find(c=>c.accountId===account&&c.symbol===symbol&&targetKey(c.target)===targetKey(target));
  const holding=state.holdings[account]?.[symbol];
  const events=[...(state.corrections??[])].reverse().filter(c=>(!account||c.accountId===account)&&(!symbol||c.symbol===symbol));
  const currentSelection=view.correctionStates.filter(c=>(!account||c.accountId===account)&&(!symbol||c.symbol===symbol));
  useEffect(()=>{setPreview(null);setReviewed(false);},[account,symbol,section,field,row,value,unknown,reason,kind,state.revision]);
  async function run(action){setBusy(true);setError('');setMessage('');try{await action();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  function edit(c,withdraw){setAccount(c.accountId);setSymbol(c.symbol);setSection(c.target.section);setField(c.target.field);setRow(c.target.row??0);setValue(c.value??'');setUnknown(c.value===null);setKind(withdraw?'revoke':'set');setReason('');setPreview(null);}
  return <>
    <Alert severity="info">Corrections change the reviewed view of a holding. Original imports remain available in History. Each accepted change records your sign-in, time, reason, and supporting evidence. Changed source evidence suspends the correction until you review it.</Alert>
    {error&&<Alert severity="error">{error}</Alert>}{message&&<Alert severity="success">{message}</Alert>}
    <section className="card"><h2>Review a correction</h2><Button disabled={busy} onClick={()=>run(async()=>onChanged(await store.readState()))}>Refresh correction evidence</Button>
      <div className="form-grid">
        <TextField select label="Correction account" value={account} disabled={busy} onChange={e=>{setAccount(e.target.value);setSymbol('');setKind('set');}}><MenuItem value="">Choose an account</MenuItem>{state.accounts.map(a=><MenuItem key={a.id} value={a.id}>{a.portfolioName?`${a.portfolioName} / `:''}{a.label}</MenuItem>)}</TextField>
        <TextField select label="Correction security" value={symbol} disabled={busy} onChange={e=>{setSymbol(e.target.value);setRow(0);setKind('set');}}><MenuItem value="">Choose a holding</MenuItem>{Object.keys(state.holdings[account]??{}).sort().map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField>
        <TextField select label="Evidence section" value={section} disabled={busy} onChange={e=>{setSection(e.target.value);setField(correctionFields[e.target.value][0]);setKind('set');}}>{Object.keys(correctionFields).map(s=><MenuItem key={s} value={s}>{s==='lots'?'Lot scope':s==='lot'?'Individual lot':s==='holding'?'Currency confirmation':'Position'}</MenuItem>)}</TextField>
        <TextField select label="Correction field" value={field} disabled={busy} onChange={e=>{setField(e.target.value);setKind('set');}}>{correctionFields[section].map(f=><MenuItem key={f} value={f}>{fieldLabel(f)}</MenuItem>)}</TextField>
        {section==='lot'&&<TextField select label="Accepted lot row" value={row} disabled={busy||kind==='revoke'} onChange={e=>setRow(Number(e.target.value))}>{(holding?.lotScope?.lots??[]).map((l,i)=><MenuItem key={i} value={i}>Row {i+1} · source {l.row_ref??'?'} · {l.acquisition_date??'unknown date'} · {l.quantity} shares · basis {l.total_basis??'unknown'}</MenuItem>)}{row>=(holding?.lotScope?.lots.length??0)&&<MenuItem value={row}>Former row {row+1} — source row no longer available</MenuItem>}</TextField>}
      </div>
      {holding&&<details><summary>Original accepted evidence for {symbol}</summary><p>Position: {display(holding.position.quantity)} shares · basis {display(holding.position.total_basis)} · effective {display(holding.position.effective_at??holding.position.effective_date)} · currency {display(holding.confirmedCurrency??holding.position.currency)}.</p><p>Lot scope: effective {display(holding.lotScope?.effective_at??holding.lotScope?.effective_date)} · reported quantity {display(holding.lotScope?.reported_totals.quantity)} · reported basis {display(holding.lotScope?.reported_totals.total_basis)}.</p><div className="table-wrap" style={{maxHeight:350,overflow:'auto'}}><table><thead><tr><th>Row / source reference</th><th>Acquired</th><th>Quantity</th><th>Basis</th><th>Cost per share</th></tr></thead><tbody>{(holding.lotScope?.lots??[]).map((l,i)=><tr key={i}><td>{i+1} / {l.row_ref??'Unknown'}</td><td>{display(l.acquisition_date)}</td><td>{display(l.quantity)}</td><td>{display(l.total_basis)}</td><td>{display(l.cost_per_share)}</td></tr>)}</tbody></table></div><p>Complete original files are available in History and Reconciliation.</p></details>}
      <p>Selected field: {label(target)}. {current?`Existing correction is ${current.status==='active'?'applied':'suspended pending review'}.`:'No current correction for this field.'}</p>
      <TextField select label="Correction action" value={kind} disabled={busy} onChange={e=>setKind(e.target.value)}><MenuItem value="set">Set reviewed value</MenuItem><MenuItem value="revoke" disabled={!current}>Withdraw existing correction</MenuItem></TextField>
      {kind==='set'&&<><TextField sx={{m:1}} label="Reviewed value" value={value} disabled={busy||unknown} onChange={e=>setValue(e.target.value)} helperText={field.includes('date')?'YYYY-MM-DD; use only a date you verified.':field==='confirmedCurrency'?'Three-letter currency code, e.g. USD.':'Exact decimal, without currency signs or commas.'}/><FormControlLabel control={<Checkbox checked={unknown} disabled={busy} onChange={e=>setUnknown(e.target.checked)}/>} label="Value is unknown"/></>}
      <TextField fullWidth multiline minRows={2} label="Correction reason" value={reason} disabled={busy} onChange={e=>setReason(e.target.value)} helperText="Describe what you checked and why the imported value needs correction. At least 3 characters."/>
      <Button variant="contained" disabled={busy||!holding||reason.trim().length<3} onClick={()=>run(async()=>{setPreview(null);setReviewed(false);setPreview(await store.prepareCorrection({baseRevision:state.revision,accountId:account,symbol,target,kind,value:unknown?null:value,reason,previousId:current?.id??null}));})}>Preview correction</Button>
      {preview&&<div className="acceptance"><h3>Confirm reviewed change</h3><p>{symbol} · {label(preview.record.target)} · {preview.record.kind==='revoke'?'Withdrawal':'Correction'}</p><div className="table-wrap"><table><thead><tr><th>Imported value</th><th>Currently displayed</th><th>After acceptance</th></tr></thead><tbody><tr><td>{display(preview.imported)}</td><td>{display(preview.before)}</td><td>{display(preview.after)}</td></tr></tbody></table></div><p>{preview.record.reason}</p>
        <FormControlLabel control={<Checkbox checked={reviewed} disabled={busy} onChange={e=>setReviewed(e.target.checked)}/>} label="I reviewed the original value, replacement, and reason."/>
        <Button variant="contained" disabled={busy||!reviewed} onClick={()=>run(async()=>{const result=await store.acceptCorrection(preview.preparedId,reviewed);onChanged(result.state);setPreview(null);setReason('');setKind('set');setMessage('Correction recorded. Original imported evidence is preserved.');})}>Accept correction</Button>
      </div>}
    </section>
    <section className="card"><h2>Current corrections</h2>{currentSelection.map(c=><div className="history" key={c.id}><div><strong>{c.symbol} · {label(c.target)}</strong><p>{c.status==='active'?'Applied':'Needs review — suspended'} · reviewed value {display(c.value)} · imported {display(c.importedValue)}</p><p>{c.reason}</p>{c.status==='conflict'&&c.target.section==='lot'&&<p>Lot source changed. Withdraw this correction, then explicitly choose a current row. Similar-looking rows are never matched automatically.</p>}</div><div><Button disabled={busy||(c.status==='conflict'&&c.target.section==='lot')} onClick={()=>edit(c,false)}>Review value</Button><Button disabled={busy} onClick={()=>edit(c,true)}>Withdraw</Button></div></div>)}{!currentSelection.length&&<p>No current corrections for this selection.</p>}</section>
    <section className="card"><h2>Correction audit history</h2><p>Filtered by the selected account and security. Withdrawals preserve earlier entries.</p>{events.map(c=><div key={c.id} className="history"><div><strong>{c.symbol} · {label(c.target)} · {c.kind==='set'?'Set':'Withdrawn'}</strong><p>{c.at} · {c.restoration?'Historical actor recorded in restored backup':'Signed-in actor'}: {c.actor}</p><p>Imported: {display(c.before)} · previous view: {display(c.effectiveBefore)} · {c.kind==='set'?`reviewed: ${display(c.value)}`:'returned to current imported evidence'}</p><p>{c.reason}</p>{c.restoration&&<p>Restored on {c.restoration.restoredAt}.</p>}</div></div>)}{!events.length&&<p>No correction events for this selection.</p>}</section>
  </>;
}
