import BenchmarkStatus from './BenchmarkStatus';
import ReplacementPreview from './ReplacementPreview';
import {brokerLossBreakdown} from './analysis/loss-summary.mjs';
import React,{useEffect,useMemo,useState} from 'react';
import {Alert,Button,Checkbox,FormControlLabel,MenuItem,TextField} from '@mui/material';
import OpportunityReview from './OpportunityReview';
import {buildCandidates,taxSources} from './analysis/candidates.mjs';
import {combineValuationPrices} from './valuation/engine.mjs';
import {browsingInputs} from './analysis/browse-inputs.mjs';
import {sumDecimals} from '../../browser-helper/src/decimal.mjs';
const show=v=>v===null||v===undefined?'Unknown':String(v);
const labels={possible_acquisition:'Possible acquisition — review',insufficient_history:'Insufficient history',no_same_symbol_acquisition_observed:'No same-symbol acquisition observed — limited records only'};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export default function LossCandidates({store,prices,providerResult,priceMode,asOf,onNavigate,initialFilter}:{initialFilter?:any,store:any,prices:any[],providerResult:any,priceMode:string,asOf:string,onNavigate:(v:string)=>void}){
  const [previewMode,setPreviewMode]=useState(()=>{try{return localStorage.getItem('tlh-replacement-mode')==='index'?'index':'stock';}catch{return 'stock';}});
  const [expanded,setExpanded]=useState('');
  const [review,setReview]=useState<any>(null);
  const [settingsOpen,setSettingsOpen]=useState(false);
  const onReview=context=>setReview({...context,mode:previewMode});
  const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ordinary,setOrdinary]=useState(false),[search,setSearch]=useState(initialFilter?.symbol??''),[all,setAll]=useState(false),[account,setAccount]=useState(initialFilter?.accountId??''),[page,setPage]=useState(0);
  const [browsing,setBrowsing]=useState(true),[selectedHolding,setSelectedHolding]=useState(initialFilter?.symbol&&initialFilter?.accountId?JSON.stringify([initialFilter.accountId,initialFilter.symbol]):'');
  async function load(){setBusy(true);setError('');setData(null);try{
    const [state,inputs,activity,quotes]=await Promise.all([store.readState(),store.analysis({action:'read'}),store.activity({action:'read'}),priceMode==='scenario'?Promise.resolve({items:[]}):store.quotes({action:'read',...(providerResult?.provider==='Twelve Data'?{provider:'twelve-data'}:{})}).catch(()=>({items:[],loadError:'Cached prices could not be loaded. Reload saved data to retry.'}))]);
    const inventory=a=>JSON.stringify(a.map(x=>[x.id,x.type]).sort((a,b)=>a[0].localeCompare(b[0])));
    if(inventory(state.accounts)!==inventory(inputs.accounts)||inventory(state.accounts)!==inventory(activity.accounts))throw new Error('Accounts changed during loading. Refresh analysis evidence.');
    setData({state,inputs,activity,quotes,today:today(),loadedAt:new Date().toISOString()});
  }catch(e:any){setError(e.message);}finally{setBusy(false);}}
  useEffect(()=>{load();},[store,priceMode,providerResult]);
  const result=useMemo(()=>{if(!data)return null;try{return {value:buildCandidates({state:data.state,prices:combineValuationPrices(data.state,prices,data.quotes.items,asOf,priceMode),asOf,input:browsing?browsingInputs(data.inputs.input,data.state.accounts,data.today):data.inputs.input,activity:data.activity.state,today:data.today,ordinaryPurchase:ordinary}),error:null};}catch(e:any){return {value:null,error:e.message};}},[data,prices,priceMode,asOf,ordinary,browsing]);
  const report=result?.value,visible=(report?.rows??[]).filter(r=>(all||r.candidate)&&(!selectedHolding||JSON.stringify([r.accountId,r.symbol])===selectedHolding)&&(!account||r.accountId===account)&&r.symbol.toLowerCase().includes(search.toLowerCase()));
  const eligibleLosses=visible.filter(r=>r.candidate&&r.loss!==null);
  const lossTotals=brokerLossBreakdown(eligibleLosses);
  const termLabel=t=>t==='short'?'Short-term':t==='long'?'Long-term':'Not supplied / unrecognized';
  const groups=[...new Set(visible.map(r=>JSON.stringify([r.accountId,r.symbol])))].map(key=>{const rows=visible.filter(r=>JSON.stringify([r.accountId,r.symbol])===key);return {key,first:rows[0],rows,loss:sumDecimals(rows.map(r=>r.loss))};});
  const grouped=browsing&&!selectedHolding&&!all,pages=Math.max(1,Math.ceil((grouped?groups.length:visible.length)/25)),current=Math.min(page,pages-1);
  const setup=report?[...(!report.input.analysisDate?['Choose a proposed sale date.']:[]),...(report.input.minLoss.amount===null?['Set a minimum loss per lot (0 includes every calculated loss).']:[]),...(!report.input.accounts.some(a=>a.scope==='include'&&data.state.accounts.find(s=>s.id===a.accountId)?.type==='taxable')?['Review and include a taxable account.']:[])]:[];
  const renderLots=(rows:any[])=>(<div className="table-wrap"><table aria-label="Loss candidates"><thead><tr><th>Account / security / lot</th><th>Quantity / basis</th><th>Scenario loss</th><th>Holding period</th><th>Screening</th><th>Evidence and explanation</th></tr></thead><tbody>{rows.map(r=><tr key={r.key}>
          <td>{r.accountLabel} / {r.symbol}<small>{r.rowRef??'No lots'} · row {r.index===null?'—':r.index+1}</small><small>{r.candidate?'Candidate for review':'Excluded'}</small></td><td>{show(r.quantity)}<small>{show(r.basis)} {r.currency}</small></td><td>{show(r.loss)} {r.currency}<small>Price {show(r.price?.price)} · {r.price?.kind??'none'} · {r.priceStatus}</small></td><td><strong>Broker: {r.brokerTerm?.trim()||'Not supplied'}</strong><small>As reported in the imported lot source</small><p>Calculated: {r.index===null?'No lot evidence':!ordinary?'Assumption needed':r.term.term==='unknown'?'Needs review':r.term.term==='long'?'Long-term scenario':'Short-term scenario'}</p>{r.index!==null&&!ordinary?<a href="#opportunity-settings" onClick={()=>setSettingsOpen(true)}>Review holding-period assumption</a>:r.term.term==='unknown'&&<small>{r.term.reason}</small>}<small>Acquired {r.acquired??'Not supplied'}</small></td><td>{r.screen?labels[r.screen.status]:'Not screened'}</td>
          <td>{onReview&&<Button disabled={!r.candidate||r.currency!=='USD'||!(Number(r.marketValue)>0)} onClick={()=>onReview({accountId:r.accountId,symbol:r.symbol,amount:r.marketValue,date:report!.input.analysisDate,rowRef:r.rowRef,quantity:r.quantity,sourceId:r.sourceId,lotIndex:r.index})}>Review trade for {r.symbol} lot {r.index===null?'':r.index+1}</Button>}<details><summary>Explain {r.symbol} row {r.index===null?'without lots':r.index+1}</summary>
            {r.excluded.map((reason,i)=><p key={`e${i}`}>Excluded: {reason}</p>)}{r.warnings.map((reason,i)=><p key={`w${i}`}>Review: {reason}</p>)}<p>{r.term.reason} Broker label: {r.brokerTerm??'Unknown'}.</p>
            <p>Position dated {r.positionDate??'Unknown'}; lots dated {r.lotDate??'Unknown'}. Price reference: {r.price?.reference??'Unknown'}; market time {r.price?.observedAt??'Unknown'}.</p><p>Lot source: {r.sourceId??'Unknown'} / {r.sourceRef??'Unknown'} / {r.rowRef??'Unknown'}. Find the original under Reconciliation.</p>
            <p>Conditional tax arithmetic: {show(r.scenarioSavings)} {r.currency}. {r.savingsReason}</p>
            {r.screen&&<><p>Inclusive acquisition window: {r.screen.window.start} through {r.screen.window.end}.</p>{r.screen.gaps.map((g,i)=><p key={i}>{g}</p>)}
              <p>The candidate lot itself is excluded from snapshot replacement evidence. Matching activity may describe its original acquisition, but cannot be excluded without a transaction-to-lot link.</p>
              {[...r.screen.evidence,...r.screen.uncertainties].map((e,i)=><p key={i}>{e.kind} · {e.accountLabel} ({e.accountType}) · {e.date??'Unknown date'} · quantity {show(e.quantity)} · {e.rowRef} · {e.reason} Source: {e.batchId??e.sourceId??e.reference}.</p>)}
              <p>Record quantities are shown individually: snapshot and transaction rows may describe the same acquisition. No allocation, matched quantity, disallowed loss or basis adjustment is calculated.</p></>}
          </details></td>
        </tr>)}</tbody></table></div>);
  const inlineReview=(rows:any[])=>review?.symbol&&rows.some(r=>r.accountId===review.accountId&&r.symbol===review.symbol)?<OpportunityReview key={JSON.stringify(review)} inline store={store} initial={review} onClose={()=>setReview(null)}/>:null;
  return <><BenchmarkStatus store={store}/>
    {report?<section className="card" aria-label="Potential harvest loss total"><h1>Total potential harvest loss</h1>{lossTotals.length?lossTotals.map(t=><div key={t.currency}><p style={{fontSize:'clamp(2rem, 4vw, 3.5rem)',fontWeight:700,margin:'12px 0',lineHeight:1.15}}>{t.currency} {t.amount}</p><div className="table-wrap"><table aria-label={`Broker holding-period loss totals ${t.currency}`}><thead><tr><th>Broker-reported period</th><th>Eligible lots</th><th>Potential loss ({t.currency})</th></tr></thead><tbody>{t.buckets.map(b=><tr key={b.term}><td>{termLabel(b.term)}</td><td>{b.count}</td><td>{b.amount}</td></tr>)}</tbody></table></div></div>):<p><strong>No eligible losses in this view</strong></p>}<p>{eligibleLosses.length} eligible lot rows across {new Set(eligibleLosses.map(r=>JSON.stringify([r.accountId,r.symbol]))).size} holdings. Includes all pages matching the current account, symbol and holding filters; excluded rows are not counted.</p><p>Breakdown uses broker labels from the imported lot evidence, separately from the optional calculated holding-period scenario. Acquisition dates supplied for {eligibleLosses.filter(r=>r.acquired).length} of {eligibleLosses.length} eligible lots. Broker labels may reflect an earlier snapshot date.</p><small>Before fees and tax adjustments. Purchase-history warnings and incomplete coverage still require review; this is not a confirmed deductible loss or estimated tax savings.</small></section>:<section className="card"><h1>Total potential harvest loss</h1><p>{busy?'Loading opportunity evidence…':'Total unavailable until opportunity evidence is loaded.'}</p></section>}
    <Button onClick={()=>setReview({})}>Compare a holding</Button>
    {grouped&&<><TextField select label="Opportunity replacement strategy" value={previewMode} onChange={e=>{setPreviewMode(e.target.value);setReview(null);try{localStorage.setItem('tlh-replacement-mode',e.target.value);}catch{}}}><MenuItem value="stock">Allow index deviation</MenuItem><MenuItem value="index">Stay close to index</MenuItem></TextField><p>Replacement previews compare the losing lots shown using saved market evidence and your reviewed benchmark. No provider refresh runs automatically. Use Compare a holding to configure the benchmark or refresh missing ranking evidence.</p></>}
    {review&&!review.symbol&&<OpportunityReview store={store} initial={review.symbol?review:null} onClose={()=>setReview(null)}/>}
    <Alert severity="info">Explore lots at a loss, compare replacements and save a draft for review. Drafts do not place orders, change holdings, establish deductible losses or provide wash-sale clearance.</Alert>
    {browsing&&<div className="readiness-strip"><strong>Browse potential losses — no setup required</strong><span>Temporary view: {data?.today??'today'} · all taxable accounts · every calculated USD lot loss. Saved account exclusions and thresholds are not applied or changed. Missing or conflicting evidence remains excluded.</span></div>}
    {busy&&<p role="status">Loading holdings and saved prices…</p>}{error&&<Alert severity="error">{error}</Alert>}{result?.error&&<Alert severity="error">{result.error}</Alert>}
    {!browsing&&report&&setup.length>0&&<section className="card" aria-label="Opportunity setup required"><h2>Your holdings are loaded. Finish the opportunity setup.</h2><p>{report.positionCount} active holdings are available. They are not lost or removed; candidate rows remain excluded until the required settings are reviewed.</p><ul>{setup.map(s=><li key={s}>{s}</li>)}</ul><Button variant="contained" onClick={()=>onNavigate('Analysis inputs')}>Complete opportunity setup</Button><Button onClick={()=>setAll(true)}>Show holdings and exclusion reasons</Button></section>}
    {data?.quotes.loadError&&<Alert severity="warning">{data.quotes.loadError}</Alert>}
    <details id="opportunity-settings" className="setup-drawer" open={settingsOpen} onToggle={e=>setSettingsOpen(e.currentTarget.open)}><summary>Settings and evidence</summary><section className="card"><h2>Analysis evidence</h2><FormControlLabel control={<Checkbox checked={!browsing} onChange={e=>{setBrowsing(!e.target.checked);setSelectedHolding('');setAll(false);setPage(0);}}/>} label="Use my saved analysis settings"/><div className="table-tools"><Button onClick={()=>onNavigate('Analysis inputs')}>Set analysis inputs</Button><Button onClick={()=>onNavigate('Valuation')}>Set valuation prices</Button><Button onClick={()=>onNavigate('Activity')}>Review activity history</Button><Button onClick={()=>onNavigate('Reconciliation')}>Review holding evidence</Button><Button disabled={busy} onClick={load}>Reload saved data</Button></div>
      {busy&&<p>Loading saved inputs and evidence…</p>}{error&&<Alert severity="error">{error}</Alert>}{result?.error&&<Alert severity="error">{result.error}</Alert>}
      {data&&<p>Read at {data.loadedAt} · holdings revision {data.state.revision} · inputs revision {data.inputs.revision} · activity revision {data.activity.revision}. Refresh after changes in another tab.</p>}
      {report&&<>
      {report.reconciliation?.length>0&&<Alert severity="warning">Holdings need reconciliation for {report.reconciliation.map(r=>r.symbol).join(', ')}. Newer or same-day sales may affect the saved lots; these holdings are excluded from actionable candidates. <Button onClick={()=>onNavigate('Import')}>Update positions and lots</Button><Button onClick={()=>setAll(true)}>Show excluded rows</Button></Alert>}<p>Proposed sale date: <strong>{report.input.analysisDate??'Not set'}</strong> · per-lot minimum loss: {show(report.input.minLoss.amount)} {report.input.minLoss.currency} · valuation time: {asOf} · {priceMode==='scenario'?'Scenario prices only':'Provider prices with scenario fallback'}.</p>
        {!report.input.analysisDate&&<Alert severity="warning">Set an analysis date and account inclusion in Analysis inputs, then set prices in Valuation.</Alert>}
        <FormControlLabel control={<Checkbox checked={ordinary} onChange={e=>setOrdinary(e.target.checked)}/>} label="For this scenario, treat dated lots as ordinary purchased securities with no special holding-period adjustments."/>
        <p>Date-based terms are conditional. Gifted or inherited property, adjusted holding periods, short sales, options and special fund rules need separate review. The assumption clears when you leave this screen.</p>
      </>}
    </section></details>
    {report&&<>
      {report.reconciliation?.length>0&&<Alert severity="warning">Holdings need reconciliation for {report.reconciliation.map(r=>r.symbol).join(', ')}. Newer or same-day sales may affect the saved lots; these holdings are excluded from actionable candidates. <Button onClick={()=>onNavigate('Import')}>Update positions and lots</Button><Button onClick={()=>setAll(true)}>Show excluded rows</Button></Alert>}
      <section className="card"><h2>{grouped?'Choose a holding to explore':'Review individual lots'}</h2><p>{report.candidateCount} candidate lot rows · {report.excludedCount} excluded rows · {report.positionCount} active positions examined. Duplicate-looking lots remain separate. Position values are not added to lot losses.</p>
        {selectedHolding&&<Button onClick={()=>{setSelectedHolding('');setPage(0);}}>Back to holdings with losses</Button>}
        <div className="table-tools"><TextField label="Find candidate symbol" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/><TextField select label="Candidate account" value={account} onChange={e=>{setAccount(e.target.value);setPage(0);}} sx={{minWidth:240}}><MenuItem value="">All accounts</MenuItem>{data.state.accounts.map(a=><MenuItem key={a.id} value={a.id}>{a.label}</MenuItem>)}</TextField><FormControlLabel control={<Checkbox checked={all} onChange={e=>{setAll(e.target.checked);setPage(0);}}/>} label="Show excluded rows"/></div>
        {!visible.length&&<Alert severity="warning">No candidate rows in this view. Show excluded rows to see missing prices, inputs, lot evidence or account exclusions.</Alert>}
        {grouped?<div className="table-wrap"><table aria-label="Holdings with potential losses"><thead><tr><th>Holding</th><th>Lots shown</th><th>Potential loss</th><th>Broker holding-period evidence</th><th>Price evidence</th><th>Replacement & measured reasons</th><th>Review</th></tr></thead><tbody>{groups.slice(current*25,(current+1)*25).map(g=><React.Fragment key={g.key}><tr><td><strong>{g.first.symbol}</strong><small>{g.first.accountLabel}</small></td><td>{g.rows.length}</td><td>{show(g.loss)} {g.first.currency}<small>Losing lots only, before fees or tax adjustments</small></td><td>{brokerLossBreakdown(g.rows).flatMap(t=>t.buckets.filter(b=>b.count>0).map(b=><small key={`${t.currency}-${b.term}`}>{termLabel(b.term)}: {b.count} {b.count===1?'lot':'lots'} · {t.currency} {b.amount} loss</small>))}<small>Acquisition dates supplied: {g.rows.filter(r=>r.acquired).length}/{g.rows.length} lots</small></td><td>{g.first.price?.price} {g.first.price?.currency}<small>{g.first.price?.priceDate??g.first.price?.observedAt??'Date unknown'} · {g.first.priceStatus}</small></td><td><ReplacementPreview key={`${g.key}:${previewMode}:${data.loadedAt}`} store={store} accountId={g.first.accountId} portfolioId={data.state.accounts.find(a=>a.id===g.first.accountId)?.portfolioId} symbol={g.first.symbol} date={report.input.analysisDate} amount={sumDecimals(g.rows.map(r=>r.marketValue))} mode={previewMode} revision={data.loadedAt} currency={g.first.currency}/></td><td><small>{g.rows.some(r=>!r.candidate)?'Evidence needs attention':g.rows.some(r=>r.warnings.length)?'Review warnings':'Available for review'}</small><Button aria-expanded={expanded===g.key} aria-controls={`holding-detail-${encodeURIComponent(g.key)}`} onClick={()=>{setExpanded(expanded===g.key?'':g.key);setReview(null);}}>{expanded===g.key?'Hide':'View'} {g.first.symbol} lots</Button></td></tr>{expanded===g.key&&<tr className="expanded-holding"><td colSpan={7}><section id={`holding-detail-${encodeURIComponent(g.key)}`} aria-label={`${g.first.symbol} lots and replacements`}><h3>{g.first.symbol} · lots and replacement review</h3>{renderLots(g.rows)}{inlineReview(g.rows)}</section></td></tr>}</React.Fragment>)}</tbody></table></div>:<>{renderLots(visible.slice(current*25,(current+1)*25))}{inlineReview(visible)}</>}<div className="table-tools"><Button disabled={!current} onClick={()=>setPage(current-1)}>Previous candidates</Button><span>Page {current+1} of {pages}</span><Button disabled={current+1>=pages} onClick={()=>setPage(current+1)}>Next candidates</Button></div>

      </section>
      {report.window&&<section className="card"><h2>Coverage across every listed account</h2><p>{report.window.start} through {report.window.end}, inclusive. Omitted accounts and IRAs still contribute acquisition evidence. Collection declarations are not independently verified; a future window remains open.</p><div className="table-wrap"><table aria-label="Candidate history coverage"><thead><tr><th>Account</th><th>Supplied collection coverage</th><th>Uncovered dates</th></tr></thead><tbody>{report.coverage.map(c=><tr key={c.accountId}><td>{c.label}</td><td>{c.status.replaceAll('_',' ')}</td><td>{c.gaps.map(g=>`${g.start} through ${g.end}`).join('; ')||'No gaps in supplied declarations'}</td></tr>)}</tbody></table></div></section>}
    </>}
    <details className="setup-drawer"><summary>Scope and tax references</summary><section className="card"><h2>Scope and tax references</h2><p>Matching uses exact reported symbols and is only a warning screen. It does not establish substantially identical securities across different symbols, household ownership, options, spouse/controlled-entity activity, or final share matching. Conditional tax arithmetic excludes netting, carryovers, deduction limits, NIIT, state interactions, fees and special fund rules. It assumes the whole displayed loss receives the entered rate; it is not an estimate of deductible loss.</p><p>Rules reviewed September 18, 2026: {taxSources.map(s=><React.Fragment key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a>{' · '}</React.Fragment>)}</p></section>
    </details>
  </>;
}


