import React,{useEffect,useState,useRef} from 'react';
import {Alert,Button,Checkbox,Dialog,FormControlLabel,TextField} from '@mui/material';
import Replacements from './Replacements';
import {draftLots} from './analysis/draft-lots.mjs';
export default function OpportunityReview({store,initial,onClose,inline=false}:any){
 const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(!inline)return;const trigger=document.activeElement as HTMLElement;heading.current?.focus();return()=>{if(trigger?.isConnected)trigger.focus();};},[]);
 const [options,setOptions]=useState<any>(null),[quantities,setQuantities]=useState<any>({}),[step,setStep]=useState('lots'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<any>(null),[request,setRequest]=useState<any>(null),[reviewed,setReviewed]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{if(!initial)return;let active=true;store.replacements({action:'lot-options',accountId:initial.accountId,symbol:initial.symbol,date:initial.date}).then(o=>{if(active){setOptions(o);setQuantities({[initial.lotIndex]:initial.quantity});}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[store,initial]);
 const lots=Object.entries(quantities).map(([index,quantity])=>({index:Number(index),quantity}));let selected:any=null,selectionError='';if(options)try{selected=draftLots(options.holding,lots,options.price);}catch(e:any){selectionError=e.message;}
 async function run(work){setBusy(true);setError('');try{await work();}catch(e:any){setError(e.message);setReviewed(false);}finally{setBusy(false);}}
 const content=<>
 <div className="review-heading"><h2 ref={heading} tabIndex={-1} id="opportunity-review-title">{initial?`Review ${initial.symbol}`:'Compare a holding'}</h2><Button disabled={busy} onClick={onClose}>{inline?'Close review':'Back to opportunities'}</Button></div>
 <div className="review-content">{error&&<Alert severity="error">{error}</Alert>}
 {!initial?<><p>Explore comparisons here. To save a draft, return to the list and review a specific opportunity's lots.</p><Replacements store={store}/></>:<>
 <p>1 · Select lots → 2 · Compare → 3 · Review and save</p>
 {step==='lots'&&<><h3>Select lots and quantities</h3>{!options&&!error&&<p role="status">Loading current lots and daily price…</p>}{options&&<><p>Saved daily price: ${options.price} · {options.priceDate}. This may differ from the opportunity's price. Partial-lot basis is prorated and rounded to cents.</p><div className="table-wrap"><table aria-label="Select trade lots"><thead><tr><th>Use</th><th>Lot / acquired</th><th>Available</th><th>Shares to sell</th></tr></thead><tbody>{options.holding.lotScope?.lots?.map((l,i)=><tr key={i}><td><Checkbox slotProps={{input:{'aria-label':`Select lot ${i+1}`}}} checked={quantities[i]!==undefined} onChange={e=>setQuantities(q=>{const next={...q};if(e.target.checked)next[i]=l.quantity;else delete next[i];return next;})}/></td><td>{i+1} · {l.acquisition_date??'Unknown'}<small>{l.row_ref}</small></td><td>{l.quantity}</td><td>{quantities[i]!==undefined&&<TextField label={`Lot ${i+1} quantity`} value={quantities[i]} onChange={e=>setQuantities(q=>({...q,[i]:e.target.value}))}/>}</td></tr>)}</tbody></table></div>{selectionError&&<Alert severity="warning">{selectionError}</Alert>}{selected&&<p>{selected.quantity} shares · estimated proceeds ${selected.amount} · estimated loss ${selected.potentialLoss??'Unknown'} (negative means gain), before fees and tax adjustments.</p>}<Button variant="contained" disabled={!selected} onClick={()=>setStep('compare')}>Continue to replacements</Button></>}</>}
 {step==='compare'&&selected&&<><Button onClick={()=>setStep('lots')}>Change lots</Button><Replacements store={store} initial={{...initial,amount:selected.amount,quantity:selected.quantity,rowRef:lots.map(l=>l.index+1).join(', ')}} onChoose={(r,comparison)=>run(async()=>{const req={comparison,lots,holdingsRevision:options.holdingsRevision,replacement:r.symbol};const result=await store.replacements({action:'preview-draft',...req});setRequest(req);setPreview(result.preview);setReviewed(false);setStep('confirm');})}/></>}
 {step==='confirm'&&preview&&<><h3>{saved?'Draft saved':'Review your draft'}</h3><p>{preview.evidence.account.label}: {initial.symbol} → {preview.evidence.replacement.symbol}</p><p>{preview.evidence.selected.quantity} shares · ${preview.evidence.selected.amount} proposed replacement amount · {preview.evidence.scoring.mode==='index'?'Stay close to index':'Allow index deviation'}</p><p>Price dated {preview.evidence.price.date}. Estimated loss ${preview.evidence.selected.potentialLoss??'Unknown'} before fees and tax adjustments. Negative means gain.</p><div className="table-wrap"><table aria-label="Reviewed draft lots"><thead><tr><th>Lot</th><th>Selected / available</th><th>Estimated basis</th><th>Estimated loss</th></tr></thead><tbody>{preview.evidence.selected.lots.map(l=><tr key={l.index}><td>{l.index+1}<small>{l.acquired??'Acquired date unknown'} · {l.rowRef}</small></td><td>{l.quantity} / {l.available}</td><td>${l.basis??'Unknown'}{l.partial&&<small>Prorated</small>}</td><td>${l.potentialLoss??'Unknown'}</td></tr>)}</tbody></table></div><Alert severity="warning">This saves an unexecuted draft. Check current ownership, broker lot selection and acquisition activity before acting. A replacement score does not establish tax eligibility.</Alert>{[...preview.evidence.warnings,...preview.evidence.replacement.flags.map(f=>`${preview.evidence.replacement.symbol}: ${f}`)].map((w,i)=><p key={i}>{w}</p>)}<details><summary>Review lots, source records and comparison evidence</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(preview.evidence,null,2)}</pre></details>{saved?<Alert severity="success">Saved in Results → Sales & follow-up. No order or post-sale monitoring has been started.</Alert>:<><FormControlLabel control={<Checkbox checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>} label="I reviewed the selected lots, dated prices and evidence limitations."/><Button variant="contained" disabled={!reviewed||busy} onClick={()=>run(async()=>{await store.replacements({action:'save-draft',...request,hash:preview.hash,reviewed:true});setSaved(true);})}>Save draft</Button><Button disabled={busy} onClick={()=>{setPreview(null);setStep('compare');}}>Back to comparison</Button></>}</>}
 </>}
 </div></>;
 return inline?<section onKeyDown={e=>{if(e.key==='Escape'&&!busy){e.stopPropagation();onClose();}}} className="inline-trade-review" aria-label={`Review ${initial.symbol}`}>{content}</section>:<Dialog open onClose={()=>{if(!busy)onClose();}} aria-labelledby="opportunity-review-title" maxWidth="md" fullWidth>{content}</Dialog>;
}
