import React,{useState} from 'react';
import {Alert,Button,Checkbox,FormControlLabel,MenuItem,TextField} from '@mui/material';
import {inspectPlanning} from './analysis/planning-backup.mjs';
export default function PlanningRecovery({store,state}:any){
 const [backup,setBackup]=useState<any>(null),[data,setData]=useState<any>(null),[targets,setTargets]=useState<any[]>([]),[mapping,setMapping]=useState<any>({portfolios:{},accounts:{}}),[preview,setPreview]=useState<any>(null),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function run(fn){setBusy(true);setError('');setMessage('');try{await fn();}catch(e:any){setError(e.message);setPreview(null);setReviewed(false);}finally{setBusy(false);}}
 function change(kind,id,value){setMapping(m=>({...m,[kind]:{...m[kind],[id]:value},...(kind==='portfolios'?{accounts:{}}:{})}));setPreview(null);setReviewed(false);}
 return <section className="card"><h2>Back up and restore planning records</h2><p>Includes benchmark source files, portfolio strategies and their audit history, saved trade drafts and post-sale review history. Download this alongside your imports, Activity and Analysis inputs backups. Market caches and credentials are excluded. Limit: 10 MB, 1,000 records per category.</p>
 {error&&<Alert severity="error">{error}</Alert>}{message&&<Alert severity="success">{message}</Alert>}
 <Button disabled={busy} onClick={()=>run(async()=>{const {backup}=await store.replacements({action:'planning-export'});const url=URL.createObjectURL(new Blob([JSON.stringify(backup)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='tlh-planning-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Planning backup exported. It contains private financial evidence in plain text.');})}>Export planning backup</Button>
 <Button component="label" disabled={busy}>Choose planning backup<input hidden type="file" accept=".json" aria-label="Planning backup" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)run(async()=>{setBackup(null);setData(null);setPreview(null);setReviewed(false);if(file.size>10000000)throw Error('Planning backup limit is 10 MB.');const raw=JSON.parse(await file.text()),d=await inspectPlanning(raw),read=await store.replacements({action:'read'});setTargets(read.portfolios);setBackup(raw);setData(d);setMapping({portfolios:{},accounts:{}});});}}/></Button>
 {data&&<><p>{data.universes.length} benchmark versions · {data.strategies.length} strategies · {data.drafts.length} historical drafts · {data.events.length} strategy events · {data.saleReviews?.length??0} post-sale reviews.</p><Alert severity="info">Restore holdings and activity separately. Match each portfolio and account below. Existing strategies are never overwritten. Restored drafts remain historical references requiring fresh review; their original evidence and identifiers are preserved.</Alert>
 {data.portfolios.map(p=><TextField key={p.id} select label={`Portfolio destination for ${p.name}`} value={mapping.portfolios[p.id]??''} disabled={busy} sx={{minWidth:260,m:1}} onChange={e=>change('portfolios',p.id,e.target.value)}><MenuItem value="">Choose portfolio</MenuItem>{targets.map(t=><MenuItem key={t.id} value={t.id}>{t.name}</MenuItem>)}</TextField>)}
 {data.accounts.map(a=><TextField key={a.id} select label={`Planning account destination for ${a.label}`} value={mapping.accounts[a.id]??''} disabled={busy} sx={{minWidth:260,m:1}} onChange={e=>change('accounts',a.id,e.target.value)}><MenuItem value="">Choose account</MenuItem>{state.accounts.filter(t=>t.portfolioId===mapping.portfolios[a.portfolio_id]&&t.type===a.account_type).map(t=><MenuItem key={t.id} value={t.id}>{t.label}</MenuItem>)}</TextField>)}
 <details><summary>Inspect benchmark versions, exclusions and draft choices</summary>{data.universes.map(u=><p key={u.id}>{u.name} · {u.provenance} · {u.as_of} through {u.valid_through} · {u.member_count} members</p>)}{data.strategies.map(s=><p key={s.portfolio_id}>Strategy revision {s.revision} · exclusions {s.exclusions.join(', ')||'none'}</p>)}{data.drafts.map(d=><p key={d.id}>{d.evidence.account.label} · {d.evidence.comparison.symbol} → {d.evidence.replacement.symbol} · {d.evidence.selected.quantity} shares · ${d.evidence.selected.amount} · saved {d.saved_at}</p>)}</details>
 <Button disabled={busy||data.portfolios.some(p=>!mapping.portfolios[p.id])||data.accounts.some(a=>!mapping.accounts[a.id])} onClick={()=>run(async()=>{setReviewed(false);setPreview((await store.replacements({action:'planning-preview',backup,mapping})).preview);})}>Preview planning restore</Button></>}
 {preview&&<div className="acceptance"><h3>Review planning restore</h3>{preview.portfolios.map((p,i)=><p key={i}>{p.source} → {p.destination}</p>)}<p>{preview.counts.universes} benchmark versions, {preview.counts.strategies} strategies and {preview.counts.drafts} drafts and {preview.counts.saleReviews??0} historical post-sale reviews will be restored together. Identical records are reused. Holdings and transactions are unchanged.</p><FormControlLabel control={<Checkbox checked={reviewed} disabled={busy} onChange={e=>setReviewed(e.target.checked)}/>} label="I reviewed the planning backup and destinations; restored drafts need fresh review."/><Button disabled={busy||!reviewed} variant="contained" onClick={()=>run(async()=>{const result=await store.replacements({action:'planning-restore',backup,mapping,hash:preview.hash,reviewed});setPreview(null);setReviewed(false);setMessage(result.restore.duplicate?'This planning backup was already restored to these destinations.':'Planning records restored. Review dated strategies before comparing; historical drafts are in Tracking.');})}>Restore planning records</Button></div>}
 </section>;
}
