import React,{useState} from 'react';
import {Alert,Button,Checkbox,FormControlLabel,MenuItem,TextField} from '@mui/material';
export default function RealizedRecovery({store,accounts,onRestored}:any){
 const [backup,setBackup]=useState<any>(null),[mapping,setMapping]=useState<any>({}),[preview,setPreview]=useState<any>(null),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function run(fn){setBusy(true);setError('');setMessage('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <details className="setup-drawer"><summary>Back up or restore full realized history</summary><p>Backups include all your realized accounts, original CSVs, report status and acceptance/retirement history. Store the file privately. Restore each source into a separate taxable account with no realized history. Existing holdings and transactions are unchanged. Backup checksums detect corruption, not authenticity; review the source and history.</p>
 {error&&<Alert severity="error">{error}</Alert>}{message&&<Alert severity="success">{message}</Alert>}
 <Button disabled={busy} onClick={()=>run(async()=>{const {backup}=await store.replacements({action:'realized-backup'}),url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='tlh-realized-history.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}>Download full realized backup</Button>
 <Button component="label" disabled={busy}>Choose realized backup<input type="file" hidden accept=".json" aria-label="Realized history backup" onChange={e=>{const f=e.target.files?.[0];e.target.value='';setBackup(null);setPreview(null);setMapping({});setReviewed(false);if(f)run(async()=>{if(f.size>10000000)throw Error('Choose a backup below 10 MB.');const b=JSON.parse(await f.text());if(b.kind!=='tlh-realized-history'||!Array.isArray(b.accounts))throw Error('Choose a realized history backup.');setBackup(b);});}}/></Button>
 {backup?.accounts.map(a=><TextField fullWidth select key={a.id} label={`Restore realized account ${a.label}`} value={mapping[a.id]??''} disabled={busy} onChange={e=>{setMapping({...mapping,[a.id]:e.target.value});setPreview(null);setReviewed(false);}}><MenuItem value="">Choose destination</MenuItem>{accounts.filter(a=>a.type==='taxable').map(d=><MenuItem key={d.id} value={d.id}>{d.label}</MenuItem>)}</TextField>)}
 <Button disabled={busy||!backup} onClick={()=>run(async()=>{setReviewed(false);setPreview((await store.replacements({action:'realized-restore-preview',backup,mapping})).preview);})}>Preview history restore</Button>
 {preview&&<><p>{preview.count} reports: {preview.active} active, {preview.count-preview.active} historical. {preview.duplicate?'Already restored; no records will be added.':'Original timestamps and retirement reasons will be preserved.'}</p>{preview.accounts.map((a,i)=><p key={i}>{a.source} → {a.destination}</p>)}<details><summary>Review backed-up report history</summary>{backup.reports.map(r=><div key={r.id}><strong>{r.name}</strong><p>{r.active?'Active':'Historical'} · {r.document.start} through {r.document.end} · accepted {r.accepted_at}</p>{r.retired_at&&<p>Retired {r.retired_at}: {r.retirement_reason}</p>}<p>{r.document.rows.length} lots · reported loss USD {r.document.summary.loss} · net USD {r.document.summary.net}</p></div>)}</details><FormControlLabel control={<Checkbox checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>} label="I reviewed the backup history and destination accounts."/><Button disabled={busy||!reviewed} onClick={()=>run(async()=>{await store.replacements({action:'realized-restore',backup,mapping,hash:preview.hash,reviewed:true});setPreview(null);setReviewed(false);await onRestored();setMessage('Realized history restored. Original timestamps are retained with separate restore provenance.');})}>Restore realized history</Button></>}
 </details>;
}
