import React,{useEffect,useMemo,useState} from 'react';
import {Alert,Button,Checkbox,FormControlLabel} from '@mui/material';
import {reconcileRealized} from './realized/reconciliation.mjs';
export default function RealizedReconciliation({store,reports,accounts,year}:any){
 const [activity,setActivity]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[onlyIssues,setOnlyIssues]=useState(true),[page,setPage]=useState(0);
 async function load(){setBusy(true);setError('');setActivity(null);try{setActivity((await store.activity({action:'read'})).state);}catch{setError('Transaction history could not be loaded. Retry reconciliation.');}finally{setBusy(false);}}
 useEffect(()=>{load();},[store,reports]);useEffect(()=>setPage(0),[reports,accounts,year,onlyIssues]);
 const rows=useMemo(()=>activity?reconcileRealized(reports,activity,accounts.filter(a=>a.type==='taxable'),year):[],[reports,activity,accounts,year]),matched=rows.filter(r=>r.status==='Totals match').length,visible=onlyIssues?rows.filter(r=>r.status!=='Totals match'):rows,current=Math.min(page,Math.max(0,Math.ceil(visible.length/25)-1));
 return <details className="setup-drawer"><summary>Reconcile realized reports with sales</summary><p>Matches exact account, symbol and trade date, summing all lots and sales that day. Uses active reports and accepted activity in the selected year and accounts. Totals matching does not establish individual lot allocation, complete history or tax eligibility. Proceeds are compared with Activity cash; fees and rounding differences remain visible.</p><Button disabled={busy} onClick={load}>Refresh sale reconciliation</Button>{error&&<Alert severity="error">{error}</Alert>}{busy?<p>Loading sale evidence…</p>:activity&&<><p role="status">{matched} daily groups match; {rows.length-matched} need evidence or review.</p><FormControlLabel control={<Checkbox checked={onlyIssues} onChange={e=>setOnlyIssues(e.target.checked)}/>} label="Show only reconciliation exceptions"/>{!visible.length&&<p>{rows.length?'No exceptions in this view.':'No sale or realized evidence in this view.'}</p>}<div className="table-wrap"><table aria-label="Realized sale reconciliation"><thead><tr><th>Account / security / date</th><th>Quantity: lots / sales</th><th>USD: proceeds / cash</th><th>Status and next action</th><th>Source evidence</th></tr></thead><tbody>{visible.slice(current*25,current*25+25).map(r=><tr key={r.key}><td>{accounts.find(a=>a.id===r.accountId)?.label} / {r.symbol??'Unknown symbol'}<small>{r.date??'Unknown date'}</small></td><td>{r.lots.length?r.lotQuantity:'—'} / {r.sales.length?r.saleQuantity??'Unknown':'—'}<small>Difference: {r.quantityDifference??'Not comparable'}</small></td><td>{r.lots.length?r.proceeds:'—'} / {r.sales.length?r.cash??'Unknown':'—'}<small>Difference: {r.proceedsDifference??'Not comparable'}</small></td><td><strong>{r.status}</strong><p>{r.action}</p>{r.coverage!=='covered_in_supplied_records'&&<small>Activity coverage is incomplete or uncertain.</small>}</td><td><details><summary>{r.lots.length} lots / {r.sales.length} sales</summary>{r.lots.map(l=><p key={`${l.reportId}:${l.row}`}>{l.reportName} · row {l.row} · acquired {l.opened} · quantity {l.quantity} · proceeds {l.proceeds}</p>)}{r.sales.map(s=><p key={s.id}>{s.reference} · {s.rowRef} · quantity {s.quantity??'Unknown'} · cash {s.cashAmount??'Unknown'} {s.currency??'Unknown currency'}</p>)}</details></td></tr>)}</tbody></table></div><Button disabled={current===0} onClick={()=>setPage(current-1)}>Previous reconciliations</Button><span>{visible.length?current*25+1:0}–{Math.min((current+1)*25,visible.length)} of {visible.length}</span><Button disabled={(current+1)*25>=visible.length} onClick={()=>setPage(current+1)}>Next reconciliations</Button></>}</details>;
}
