import React,{useMemo,useState} from 'react';
import {realizedSeries} from './realized/series.mjs';
const money=v=>'$'+Number(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const compact=v=>'$'+Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(v);
export default function RealizedCharts({reports,accounts,year}:any){
 const series=useMemo(()=>realizedSeries(reports,accounts.filter(a=>a.type==='taxable').map(a=>a.id),year),[reports,accounts,year]),[point,setPoint]=useState<number|null>(null);
 const daily=series.daily,monthly=series.monthly,selected=daily[Math.min(point??daily.length-1,daily.length-1)];
 if(!monthly.length)return null;
 const left=64,right=700,top=24,bottom=200,first=daily.length?Date.parse(daily[0].date):0,last=daily.length?Date.parse(daily[daily.length-1].date):0,max=Math.max(1,...daily.map(d=>Number(d.loss))),x=d=>left+(Date.parse(d.date)-first)/Math.max(86400000,last-first)*(right-left),y=v=>bottom-Number(v)/max*(bottom-top);
 const path=daily.map((d,i)=>i===0?`M ${x(d)} ${y(d.loss)}`:`H ${x(d)} V ${y(d.loss)}`).join(' '),barMax=Math.max(1,...monthly.flatMap(m=>[Number(m.loss),Number(m.gains)])),slot=(right-left)/monthly.length;
 return <div className="realized-charts"><section aria-label="Cumulative realized losses chart"><div className="chart-heading"><h3>Losses over time</h3><span>{selected?`${selected.date} · ${money(selected.loss)}`:'No reported losing lots'}</span></div><p>Cumulative losses reported in accepted lots · {year} · USD</p>{daily.length>0&&<><svg viewBox="0 0 740 244" role="img" aria-label={`Cumulative reported losses end at ${money(daily[daily.length-1].loss)} on ${daily[daily.length-1].date}`}>
 {[0,.5,1].map(f=><g key={f}><line x1={left} x2={right} y1={y(max*f)} y2={y(max*f)} stroke="#e4e8de"/><text x={left-9} y={y(max*f)+4} textAnchor="end">{compact(max*f)}</text></g>)}
 <path d={path} fill="none" stroke="#426e35" strokeWidth="3"/>{daily.map((d,i)=><circle key={d.date} cx={x(d)} cy={y(d.loss)} r={selected===d?5:3} fill="#426e35" onMouseEnter={()=>setPoint(i)}><title>{d.date}: {money(d.loss)}</title></circle>)}
 <text x={left} y="232">{daily[0].date}</text><text x={right} y="232" textAnchor="end">{daily[daily.length-1].date}</text></svg><label className="chart-slider">Explore sale dates<input type="range" min="0" max={Math.max(0,daily.length-1)} value={Math.min(point??daily.length-1,daily.length-1)} onChange={e=>setPoint(Number(e.target.value))} aria-valuetext={selected?`${selected.date}: ${money(selected.loss)}`:''}/></label></>}
 <p>Steps show reported sale dates, not portfolio performance. Missing history is not assumed to be zero.</p></section>
 <section aria-label="Monthly realized results chart"><div className="chart-heading"><h3>Gains & losses by month</h3><span><b className="chart-gains">●</b> Gains <b className="chart-losses">●</b> Losses</span></div><p>Both shown as positive amounts · USD · * incomplete report coverage</p><svg viewBox="0 0 740 250" role="img" aria-label="Monthly reported gains and losses; exact values and coverage are available in the chart data table">
 {[0,.5,1].map(f=><g key={f}><line x1={left} x2={right} y1={bottom-f*(bottom-top)} y2={bottom-f*(bottom-top)} stroke="#e4e8de"/><text x={left-9} y={bottom-f*(bottom-top)+4} textAnchor="end">{compact(barMax*f)}</text></g>)}
 {monthly.map((m,i)=><g key={m.month}>{[m.gains,m.loss].map((v,j)=><rect key={j} x={left+i*slot+slot*.17+j*slot*.32} y={bottom-Number(v)/barMax*(bottom-top)} width={slot*.27} height={Number(v)/barMax*(bottom-top)} fill={j?'#426e35':'#b2cf75'}><title>{m.month}: {j?'losses':'gains'} {money(v)}{m.complete?'':' (partial coverage)'}</title></rect>)}{!m.complete&&!m.observed&&<text x={left+(i+.5)*slot} y={bottom-10} textAnchor="middle">?</text>}<text x={left+(i+.5)*slot} y="230" textAnchor="middle">{m.month.slice(5)}{m.complete?'':'*'}</text></g>)}
 </svg></section><details className="dashboard-detail"><summary>Chart data & coverage</summary><div className="table-wrap"><table aria-label="Realized time series data"><thead><tr><th>Month</th><th>Losses</th><th>Gains</th><th>Net</th><th>Coverage</th></tr></thead><tbody>{monthly.map(m=><tr key={m.month}><td>{m.month}</td><td>{m.complete||m.observed?money(m.loss):'Unknown'}</td><td>{m.complete||m.observed?money(m.gains):'Unknown'}</td><td>{m.complete||m.observed?money(m.net):'Unknown'}</td><td>{m.complete?'Full month for selected accounts':'Partial or missing reports'}</td></tr>)}</tbody></table></div></details></div>;
}
