import RealizedCharts from './RealizedCharts';
import RealizedReconciliation from './RealizedReconciliation';
import RealizedRecovery from './RealizedRecovery';
import React,{useEffect,useState} from 'react';
import {Alert,Button,Checkbox,FormControlLabel,MenuItem,TextField} from '@mui/material';
import {summarizeRealized} from './realized/engine.mjs';
export default function RealizedLosses({store,accounts,onTracking,initialFile,onFileConsumed,importOnly=false}:any){
 const [importOpen,setImportOpen]=useState(false);
 useEffect(()=>{if(initialFile){setFile(initialFile);setPreview(null);setReviewed(false);setImportOpen(true);onFileConsumed?.();}},[initialFile]);
 const [reports,setReports]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[account,setAccount]=useState(''),[file,setFile]=useState<any>(null),[preview,setPreview]=useState<any>(null),[reviewed,setReviewed]=useState(false),[message,setMessage]=useState(''),[reason,setReason]=useState(''),[year,setYear]=useState(String(new Date().getFullYear()));
 const load=async()=>{const r=await store.replacements({action:'realized-read'});setReports(r.reports);setLoaded(true);};
 const run=async(fn)=>{setBusy(true);setError('');setMessage('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 useEffect(()=>{run(load);},[store]);
 const allowed=new Set(accounts.filter(a=>a.type==='taxable').map(a=>a.id)),active=reports.filter(r=>r.active&&allowed.has(r.account_id)),included=active.flatMap(r=>r.document.rows).filter(r=>r.closed.startsWith(year+'-')),summary=summarizeRealized(included),covered=active.filter(r=>r.document.start<=`${year}-12-31`&&r.document.end>=`${year}-01-01`);
 const cash=v=>'$'+Number(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
 return <section className="card realized-card" aria-label="Loss harvested so far"><h2>{importOnly?'Review your realized export':'Loss harvested so far'}</h2>{error&&<Alert severity="error">{error} Refresh to confirm saved state.</Alert>}{message&&<Alert severity="success">{message}</Alert>}
 {!importOnly&&<>
 <TextField sx={{minWidth:180}} select label="Realized reporting year" value={year} onChange={e=>setYear(e.target.value)}>{[...new Set([String(new Date().getFullYear()),...active.flatMap(r=>r.document.rows.map(row=>row.closed.slice(0,4)))])].sort().reverse().map(y=><MenuItem key={y} value={y}>{y}</MenuItem>)}</TextField>
 <p style={{fontSize:'2rem',fontWeight:700}}>{!loaded?'Loading realized evidence…':!covered.length?'Not established':cash(summary.loss)}</p>
 {covered.length>0&&<><p>Broker-reported losses on losing lots · {year} · USD · {summary.lots} closed lot rows in accepted reports.</p><details className="dashboard-detail"><summary>Gains, holding periods & report coverage</summary><div className="table-wrap"><table aria-label="Realized results"><thead><tr><th>Reported losses</th><th>Reported gains</th><th>Net gain/loss</th><th>Short-term net</th><th>Long-term net</th></tr></thead><tbody><tr>{[summary.loss,summary.gains,summary.net,summary.short,summary.long].map((v,i)=><td key={i}>{cash(v)}</td>)}</tr></tbody></table></div><p>{summary.washRows} rows marked wash sale. Explicit disallowed-loss amounts: {cash(summary.disallowed)}; {summary.blankDisallowed} blank fields remain unspecified. These amounts are not subtracted again from broker-reported gain/loss.</p>{covered.map(r=><p key={r.id}>{accounts.find(a=>a.id===r.account_id)?.label}: report covers {r.document.start} through {r.document.end}.</p>)}</details></>}
 <p>Realized report totals follow the portfolio/account filters and reporting year. They do not prove harvesting intent or deductible tax losses. Missing periods and accounts are not assumed to be zero. Activity sales are not added to these totals.</p>
 {loaded&&<RealizedCharts key={year} reports={reports} accounts={accounts} year={year}/>}
 <Button disabled={busy} onClick={()=>run(load)}>Refresh realized reports</Button><Button onClick={onTracking}>Review submitted sales</Button>
 {loaded&&<RealizedReconciliation store={store} reports={reports} accounts={accounts} year={year}/>}
 </>}
 <details className="setup-drawer" open={importOpen} onToggle={e=>setImportOpen(e.currentTarget.open)}><summary>Import or manage realized gain/loss reports</summary><p>Choose Schwab Export Details Only. Confirm the source account, USD and complete selected range. A newer report covering an existing range replaces it after review, preserving the previous original.</p>
 <TextField sx={{minWidth:260,maxWidth:'100%'}} select label="Realized report account" value={account} disabled={busy} onChange={e=>{setAccount(e.target.value);setPreview(null);setReviewed(false);}}><MenuItem value="">Choose taxable account</MenuItem>{accounts.filter(a=>a.type==='taxable').map(a=><MenuItem key={a.id} value={a.id}>{a.label}</MenuItem>)}</TextField>
 <Button component="label" disabled={busy}>Choose realized CSV<input type="file" hidden accept=".csv" aria-label="Realized Details CSV" onChange={e=>{const f=e.target.files?.[0];e.target.value='';setPreview(null);setReviewed(false);setFile(null);if(f)run(async()=>{if(f.size>1000000)throw Error('Choose a CSV below 1 MB.');setFile({name:f.name,text:new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await f.arrayBuffer())});});}}/></Button>{file&&<p>{file.name}</p>}
 <Button disabled={busy||!file||!allowed.has(account)} onClick={()=>run(async()=>{setReviewed(false);setPreview((await store.replacements({action:'realized-preview',accountId:account,...file})).preview);})}>Preview realized report</Button>
 {preview&&<div className="acceptance"><h3>Review realized report</h3><p>{preview.document.sourceAccount} → {preview.account.label} · {preview.document.start} through {preview.document.end}</p><p>{preview.document.rows.length} lot rows. Losses {cash(preview.document.summary.loss)}; gains {cash(preview.document.summary.gains)}; net {cash(preview.document.summary.net)}.</p><p>{preview.duplicate?'Already accepted; no duplicate lots will be added.':`${preview.replaces.length} overlapping active report(s) will be replaced.`}</p><details><summary>First 20 lot rows</summary>{preview.document.rows.slice(0,20).map(r=><p key={r.row}>{r.symbol} · {r.closed} · {r.quantity} shares · {r.term} · gain/loss {cash(r.gainLoss)}</p>)}</details><FormControlLabel control={<Checkbox checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>} label="I verified the account, USD amounts, complete report range and any replacements."/><Button disabled={busy||!reviewed} onClick={()=>run(async()=>{await store.replacements({action:'realized-accept',accountId:account,...file,hash:preview.hash,reviewed});setPreview(null);setReviewed(false);setFile(null);await load();setMessage('Realized report accepted. Original evidence is retained.');})}>Accept realized report</Button></div>}
 <TextField label="Report withdrawal reason" value={reason} onChange={e=>setReason(e.target.value)} fullWidth/>
 {reports.filter(r=>allowed.has(r.account_id)).map(r=><div className="history" key={r.id}><div><strong>{r.name}</strong><p>{r.active?'Active':'Historical'} · {r.document.start} through {r.document.end} · {r.retirement_reason??''}</p><p>Accepted: {r.accepted_at}{r.retired_at?` · Retired: ${r.retired_at}`:''}</p>{r.provenance&&<details><summary>Restore provenance</summary><pre>{JSON.stringify(r.provenance,null,2)}</pre></details>}</div><Button disabled={busy} onClick={()=>run(async()=>{const src=await store.replacements({action:'realized-original',id:r.id}),url=URL.createObjectURL(new Blob([src.source_text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=src.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}>Download original CSV</Button>{r.active&&<Button disabled={busy||reason.trim().length<3} onClick={()=>run(async()=>{await store.replacements({action:'realized-withdraw',id:r.id,reason});setPreview(null);await load();setMessage('Report withdrawn; original history is retained.');})}>Withdraw report</Button>}</div>)}
 <RealizedRecovery store={store} accounts={accounts} onRestored={load}/>
 </details></section>;
}
