import BenchmarkStatus from './BenchmarkStatus';
import React,{useEffect,useState,useRef} from 'react';
import {Alert,Button,Checkbox,FormControlLabel,MenuItem,TextField} from '@mui/material';
import {universeTemplate} from './analysis/replacements.mjs';
const download=(name,text)=>{const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
export default function Replacements({store,initial,onBack,onChoose}:any){
  const [data,setData]=useState<any>(null),[state,setState]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [file,setFile]=useState<any>(null),[preview,setPreview]=useState<any>(null),[reviewed,setReviewed]=useState(false);
  const [portfolio,setPortfolio]=useState(''),[universe,setUniverse]=useState(''),[exclusions,setExclusions]=useState(''),[strategyReviewed,setStrategyReviewed]=useState(false),[holding,setHolding]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10));
  const [report,setReport]=useState<any>(null),[page,setPage]=useState(0),[showExcluded,setShowExcluded]=useState(false);
  const [mode,setMode]=useState(initial?.mode??'stock'),[amount,setAmount]=useState('1000'),[poolLimit,setPoolLimit]=useState(20),[progress,setProgress]=useState('');
  const stop=useRef(false);useEffect(()=>()=>{stop.current=true;},[]);
  const seeded=useRef(false);
  async function load(){const [d,s]=await Promise.all([store.replacements({action:'read'}),store.readState()]);setData(d);setState(s);return d;}
  useEffect(()=>{load().catch(e=>setError(e.message));},[store]);
  useEffect(()=>{if(!data||!state||seeded.current)return;seeded.current=true;const id=initial?state.accounts.find(a=>a.id===initial.accountId)?.portfolioId:data.portfolios.length===1?data.portfolios[0].id:null;if(id){choosePortfolio(id);if(initial){setHolding(JSON.stringify([initial.accountId,initial.symbol]));setAmount(String(initial.amount));if(initial.date)setDate(initial.date);}}},[data,state,initial]);
  useEffect(()=>{setReport(null);setPage(0);},[portfolio,universe,holding,date,exclusions,mode,amount,poolLimit]);
  function comparison(action='compare'){const [accountId,symbol]=JSON.parse(holding);return {action,portfolioId:portfolio,accountId,symbol,date,mode,amount,poolLimit};}
  async function enrich(){stop.current=false;setReport(null);while(!stop.current){const result=await store.replacements(comparison('enrich'));setProgress(`${result.completed} / ${result.total} market evidence requests cached${result.retryAfter?' · waiting for provider allowance':''}.`);if(result.done)break;if(result.retryAfter)for(let i=0;i<result.retryAfter&&!stop.current;i++)await new Promise(r=>setTimeout(r,1000));}if(!stop.current)setReport(await store.replacements(comparison()));else setProgress('Paused. Cached evidence is retained; refresh to resume.');}
  async function run(work){setBusy(true);setError('');setMessage('');try{await work();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  function choosePortfolio(id){setPortfolio(id);setHolding('');const strategy=data.strategies.find(s=>s.portfolio_id===id);setUniverse(strategy?.universe_id??'');setExclusions((strategy?.exclusions??[]).join(', '));setStrategyReviewed(false);}
  const strategy=data?.strategies.find(s=>s.portfolio_id===portfolio),selected=data?.universes.find(u=>u.id===universe);
  const active=(state?.accounts??[]).filter(a=>a.portfolioId===portfolio&&a.type==='taxable').flatMap(a=>Object.entries(state.holdings[a.id]??{}).filter(([,h]:any)=>h.active).map(([symbol])=>({accountId:a.id,symbol,label:`${a.label} / ${symbol}`})));
  const visible=report?.rows.filter(r=>showExcluded||!r.excluded.length)??[],pages=Math.max(1,Math.ceil(visible.length/25));
  return <><BenchmarkStatus store={store}/>
    <div className="journey-bar"><span>1 · Opportunity</span><strong>2 · Compare replacements</strong><span>3 · Save plan — coming next</span></div>
    {initial&&holding===JSON.stringify([initial.accountId,initial.symbol])&&<section className="trade-context"><strong>{initial.symbol} · lot {initial.rowRef} · {initial.quantity} shares</strong><p>Starting amount ${initial.amount} from the opportunity's valuation. Replacement comparisons use saved daily prices and may differ from that scenario. This is an unsaved comparison; no sale is recorded.</p>{onBack&&<Button onClick={onBack}>Back to opportunities</Button>}</section>}
    <Alert severity="info">Compare a similar stock or a trade that brings your covered stock holdings closer to the IWV index proxy. No trade is executed and no tax clearance is implied.</Alert>
    {error&&<Alert severity="error">{error}</Alert>}{message&&<Alert severity="success">{message}</Alert>}
    <details className="setup-drawer"><summary>Benchmark setup &amp; portfolio exclusions {strategy?'· saved':'· choose or set up a portfolio'}</summary>
    <section className="card"><h2>Review benchmark data</h2><p>Use the versioned JSON template for an official list, a curated list, or a clearly labeled fund-holdings proxy. ETF holdings are not verified index membership. Unknown metrics should be null.</p>
      <div className="table-tools"><Button onClick={()=>download('replacement-universe-template.json',JSON.stringify(universeTemplate(),null,2))}>Download universe template</Button><Button component="label" disabled={busy}>Choose universe JSON<input type="file" hidden aria-label="Universe JSON" accept=".json" onChange={e=>{const f=e.target.files?.[0];e.target.value='';setPreview(null);setReviewed(false);if(f)run(async()=>{if(f.size>2097152)throw Error('File limit: 2 MB.');const source={name:f.name,text:await f.text()};setFile(source);setPreview((await store.replacements({action:'preview',...source})).preview);});}}/></Button></div>
      {preview&&<><p>{preview.document.name} · {preview.document.benchmark} · {preview.document.members.length} members · {preview.document.provenance}</p><p>Snapshot / review cutoff: {preview.document.asOf} through {preview.document.validThrough}. Source: {preview.document.source}</p><details><summary>Review member data</summary><pre style={{maxHeight:320,overflow:'auto',whiteSpace:'pre-wrap'}}>{JSON.stringify(preview.document.members,null,2)}</pre></details><FormControlLabel control={<Checkbox checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>} label="I reviewed the source, provenance, dates and member data."/><Button disabled={busy||!reviewed} onClick={()=>run(async()=>{const saved=await store.replacements({action:'accept',...file,hash:preview.hash,reviewed});await load();setMessage(saved.duplicate?'This source version was already saved.':'Immutable universe version saved. Select it below.');setPreview(null);setReviewed(false);})}>Accept universe version</Button></>}
    </section>
    <section className="card"><h2>2. Choose the portfolio strategy</h2><div className="form-grid">
      <TextField select label="Replacement portfolio" value={portfolio} disabled={busy} onChange={e=>choosePortfolio(e.target.value)}><MenuItem value="">Choose portfolio</MenuItem>{data?.portfolios.map(p=><MenuItem key={p.id} value={p.id}>{p.name}</MenuItem>)}</TextField>
      <TextField select label="Membership universe version" value={universe} disabled={busy} onChange={e=>{setUniverse(e.target.value);setStrategyReviewed(false);}}><MenuItem value="">Choose universe</MenuItem>{data?.universes.map(u=><MenuItem key={u.id} value={u.id}>{u.name} · {u.as_of} · {u.hash.slice(0,8)}</MenuItem>)}</TextField>
      <TextField label="Exclude replacement symbols" value={exclusions} disabled={busy} onChange={e=>{setExclusions(e.target.value.toUpperCase());setStrategyReviewed(false);}} helperText="Comma or space separated; exact symbols."/>
    </div>{selected&&<p>Selected: {selected.benchmark} · {selected.provenance} · {selected.member_count} members · snapshot {selected.as_of}, review by {selected.valid_through}.</p>}
    <p>Saved strategy revision: {strategy?.revision??0}. Current universe: {data?.universes.find(u=>u.id===strategy?.universe_id)?.name??'None'}.</p>
    <FormControlLabel control={<Checkbox checked={strategyReviewed} onChange={e=>setStrategyReviewed(e.target.checked)}/>} label="I reviewed this portfolio universe and exclusions."/>
    <Button disabled={busy||!portfolio||!universe||!strategyReviewed} onClick={()=>run(async()=>{await store.replacements({action:'select',portfolioId:portfolio,universeId:universe,baseRevision:strategy?.revision??0,exclusions:exclusions.split(/[\s,]+/).filter(Boolean),reviewed:true});await load();setStrategyReviewed(false);setReport(null);setMessage('Portfolio strategy saved with an audit revision.');})}>Save replacement strategy</Button>
    <Button disabled={busy} onClick={()=>run(async()=>{await load();setReport(null);setStrategyReviewed(false);setMessage('Saved evidence reloaded. Review selections before saving.');})}>Reload replacement evidence</Button></section>
    </details>
    <section className="card"><h2>What would you like this trade to achieve?</h2>
    <div className="readiness-strip" role="status"><strong>{busy?'Updating comparison…':report?.scoring?`${report.scoring.ranked} candidates ready to review`:strategy?'Ready to compare saved evidence':portfolio?'Set up a benchmark for this portfolio to begin':'Choose a portfolio in Benchmark setup to begin'}</strong><span>{selected?`${selected.benchmark} · ${selected.provenance} · snapshot ${selected.as_of} · review by ${selected.valid_through}`:'No benchmark selected'}</span></div>
    <div className="form-grid"><TextField select label="Scoring strategy" value={mode} disabled={busy} onChange={e=>setMode(e.target.value)}><MenuItem value="stock">Allow index deviation — preserve stock exposure</MenuItem><MenuItem value="index">Stay close to index — IWV equity proxy</MenuItem></TextField><TextField label="Proposed replacement amount (USD)" value={amount} disabled={busy||!!onChoose} onChange={e=>setAmount(e.target.value)}/><TextField select label="Candidate pool size" value={poolLimit} disabled={busy} onChange={e=>setPoolLimit(Number(e.target.value))}>{[20,50,150].map(n=><MenuItem key={n} value={n}>{n} candidates</MenuItem>)}</TextField></div>
    <p>{mode==='stock'?'Weights: return similarity 35%, industry 25%, market cap 15%, volatility 15%, concentration 10%. Pool: same-sector stocks nearest in IWV weight; this screening proxy is not market capitalization.':'Weights: post-trade constituent alignment 50%, sector alignment 30%, stock similarity 20%. Pool: strongest preliminary improvements in constituent and sector alignment across the supported universe.'} Scenario settings reset on reload. The proposed swap reinvests the same dollar amount and does not execute a trade.</p>
    <div className="table-tools"><TextField select label="Source holding" value={holding} disabled={busy||!!onChoose} sx={{minWidth:240}} onChange={e=>setHolding(e.target.value)}><MenuItem value="">Choose taxable holding</MenuItem>{active.map(h=><MenuItem key={JSON.stringify([h.accountId,h.symbol])} value={JSON.stringify([h.accountId,h.symbol])}>{h.label}</MenuItem>)}</TextField><TextField type="date" label="Replacement analysis date" value={date} disabled={busy||!!onChoose} slotProps={{inputLabel:{shrink:true}}} onChange={e=>setDate(e.target.value)}/><Button variant="contained" disabled={busy||!holding||!strategy||strategy.universe_id!==universe||JSON.stringify(strategy.exclusions)!==JSON.stringify(exclusions.split(/[\s,]+/).filter(Boolean))} onClick={()=>run(async()=>{setReport(null);setReport(await store.replacements(comparison()));setPage(0);})}>Compare replacements</Button></div>
    <Button disabled={busy||!holding||!strategy||strategy.universe_id!==universe||JSON.stringify(strategy.exclusions)!==JSON.stringify(exclusions.split(/[\s,]+/).filter(Boolean))} onClick={()=>run(enrich)}>Refresh ranking evidence</Button>{busy&&<Button onClick={()=>{stop.current=true;}}>Pause evidence refresh</Button>}
    <p>First refresh needs up to two requests per symbol and shares the five-per-minute allowance with quotes (about nine minutes for 20 new candidates). Cached results are reused for this price date. Progress resumes after a pause; provider failures retain completed evidence. Larger pools take longer. Split-adjusted price returns exclude dividend reinvestment.</p>{progress&&<p role="status">{progress}</p>}
    {report&&<><p>{report.source.symbol} · {report.universe.benchmark} · {report.universe.provenance}. Universe version {report.universeHash.slice(0,12)} · strategy {report.strategyRevision} · holdings {report.holdingsRevision} · activity {report.activityRevision}.</p><p>Source: {report.universe.source}. Snapshot {report.universe.asOf}, review cutoff {report.universe.validThrough}.</p>{report.warnings.map((w,i)=><Alert severity="warning" key={i}>{w}</Alert>)}
    {report.scoring&&<><h3>Top five — evaluated candidates</h3>{report.scoring.top.length?<ol aria-label="Top replacement shortlist">{report.scoring.top.map(symbol=>{const r=report.rows.find(r=>r.symbol===symbol);return <li key={symbol}><strong>{symbol} · {r.score.toFixed(3)} / 100</strong> — {r.name}. {r.evidence.length} activity/snapshot records to review.{report.scoring.mode==='index'&&<span className="shortlist-impact">{r.indexChange.constituents+0.6*r.indexChange.sectors < -1e-12 ? 'Improves' : r.indexChange.constituents+0.6*r.indexChange.sectors > 1e-12 ? 'Worsens' : 'No material change to'} alignment of covered holdings with the index proxy. Expand Explain for constituent and sector changes.</span>}{onChoose&&<Button onClick={()=>onChoose(r,comparison())}>Choose {symbol}</Button>}</li>;})}</ol>:<p>No fully evidenced candidates yet. Refresh ranking evidence to build the shortlist.</p>}<p>{report.scoring.ranked} fully evidenced candidates in the selected pool of {report.scoring.pool.length}. Scores within one point are close alternatives; {report.scoring.nearCutoff} candidates are near the fifth-place cutoff. This is not a search for five guaranteed winners.</p><p>{report.scoring.scope} Valued sleeve: ${report.scoring.valuedSleeve.toFixed(2)} · omitted holdings: {report.scoring.omittedHoldings} · price and metrics date: {report.metricsAsOf}.</p><p>Missing components earn no points and block entry to the top five. Industry uses provider SIC classification. Scores are heuristic rankings, not expected returns, equivalence or tax clearance.</p></>}
    <details><summary>{report.sourceEvidence.length} source-security activity/snapshot records for review</summary>{report.sourceEvidence.map((e,i)=><p key={i}>{e.symbol} · {e.date??'Unknown date'} · {e.action} · {e.quantity??'Unknown quantity'} · {e.reference}. Account {e.accountId}.</p>)}</details>
    <FormControlLabel control={<Checkbox checked={showExcluded} onChange={e=>{setShowExcluded(e.target.checked);setPage(0);}}/>} label="Show excluded replacements"/>
    {!visible.length&&<p>No eligible comparisons. Review exclusions and universe coverage.</p>}
    <div className="table-wrap"><table aria-label="Replacement candidates"><thead><tr><th>Candidate</th><th>Strategy score</th><th>Daily price</th><th>Reasons and review</th></tr></thead><tbody>{visible.slice(page*25,(page+1)*25).map(r=><tr key={r.symbol}><td>{r.symbol}<small>{r.name} · {r.type}</small></td><td>{r.score.toFixed(3)} / 100<small>{r.knownPoints} points assessable · {r.scoreStatus}</small></td><td>{r.price?`${r.price.price} ${r.price.currency} · ${r.price.date}`:'Unknown'}</td><td><details><summary>Explain {r.symbol}</summary>{r.components&&Object.entries(r.components).map(([k,v]:any)=><p key={k}>{k}: {v===null?'Unknown':`${(v*100).toFixed(2)}% match`} · weight {report.scoring.weights[k]}%</p>)}{r.indexChange&&report.scoring.mode==='index'&&<p>Change in squared weight deviation (negative improves): constituents {r.indexChange.constituents.toFixed(6)}, sectors {r.indexChange.sectors.toFixed(6)}.</p>}<p>{r.observations??0} aligned return observations; at least 126 required.</p>{[...r.excluded,...r.reasons,...r.flags].map((v,i)=><p key={i}>{v}</p>)}{r.evidence.map((e,i)=><p key={`e${i}`}>{e.symbol} · {e.date??'Unknown date'} · {e.action} · {e.quantity??'Unknown quantity'} · {e.reference}. Account {e.accountId}.</p>)}</details></td></tr>)}</tbody></table></div><div className="table-tools"><Button disabled={!page} onClick={()=>setPage(page-1)}>Previous replacements</Button><span>Page {page+1} of {pages}</span><Button disabled={page+1>=pages} onClick={()=>setPage(page+1)}>Next replacements</Button></div></>}
    </section>
  </>;
}



