import React,{useEffect,useState} from 'react';
import {Alert,Button,Checkbox,Dialog,FormControlLabel,MenuItem,TextField,useMediaQuery} from '@mui/material';
import TradeDrafts from './TradeDrafts';
export default function SaleTracking({store,onActivity,initialSaleId,accountIds}:any){
 const mobile=useMediaQuery('(max-width:600px)');
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[inactive,setInactive]=useState(false),[page,setPage]=useState(0),[detail,setDetail]=useState<any>(null),[note,setNote]=useState(''),[disposition,setDisposition]=useState('reviewed'),[reviewed,setReviewed]=useState(false),[message,setMessage]=useState('');
 async function run(fn){setBusy(true);setError('');try{await fn();}catch(e:any){setError(e.message);setReviewed(false);}finally{setBusy(false);}}
 async function load(){setData(await store.replacements({action:'tracking-read'}));}
 useEffect(()=>{run(async()=>{await load();if(initialSaleId)await open(initialSaleId);});},[store,initialSaleId]);
 async function open(id){setNote('');setReviewed(false);setDisposition('reviewed');setMessage('');setDetail(await store.replacements({action:'tracking-detail',saleId:id}));}
 const rows=(data?.sales??[]).filter(s=>(!accountIds||accountIds.includes(s.accountId))&&(inactive||s.active&&s.accountType==='taxable')&&(s.symbol??'').toLowerCase().includes(search.toLowerCase())),current=Math.min(page,Math.max(0,Math.ceil(rows.length/25)-1)),e=detail?.evidence;
 return <><section className="card"><h1>Post-sale tracking</h1><p>Sales come directly from accepted transaction imports. No draft or trade link is required. Each sell row remains separate, including partial fills.</p><Alert severity="info">Reported sale proceeds do not establish cost basis or a realized loss. Tracking highlights records to review; it does not calculate wash-sale adjustments or certify tax clearance.</Alert>{error&&!detail&&<Alert severity="error">{error}</Alert>}{busy&&!detail&&<p role="status">Loading tracking evidence…</p>}
 <div className="table-tools"><Button disabled={busy} onClick={()=>run(load)}>Refresh sale tracking</Button><Button onClick={onActivity}>Import or review transactions</Button><TextField label="Find sale symbol" value={search} onChange={ev=>{setSearch(ev.target.value);setPage(0);}}/><FormControlLabel control={<Checkbox checked={inactive} onChange={ev=>{setInactive(ev.target.checked);setPage(0);}}/>} label="Include inactive sources and non-taxable accounts"/></div>
 {data&&<p>{rows.length} sale rows · reviewed as of {data.today} (New York date). {data.restoredReviews>0&&`${data.restoredReviews} restored historical reviews are reference-only; imported sales require fresh review.`}</p>}
 {data&&!rows.length&&<p>No sales in this view. Import Schwab transactions in Activity, then refresh tracking.</p>}
 <div className="table-wrap"><table aria-label="Tracked sales"><thead><tr><th>Sale</th><th>Shares / reported cash</th><th>Inclusive review window</th><th>Status</th><th>Review</th></tr></thead><tbody>{rows.slice(current*25,(current+1)*25).map(s=><tr key={s.id}><td><strong>{s.symbol??'Unknown symbol'}</strong><small>{s.accountLabel} · {s.date??'Date missing'}</small><small>{s.rowRef}</small></td><td>{s.quantity??'Unknown'}<small>{s.cashAmount??'Unknown'} {s.currency??''} · imported amount</small></td><td>{s.window?`${s.window.start} through ${s.window.end}`:'Date needed'}<small>{s.phase.replaceAll('_',' ')}</small></td><td>{s.reviewStatus}<small>{s.sourceStatus!=='active'&&s.sourceStatus}</small></td><td><Button disabled={busy} onClick={()=>run(()=>open(s.id))}>Review sale {s.symbol??'unknown'} {s.rowRef}</Button></td></tr>)}</tbody></table></div><Button disabled={!current} onClick={()=>setPage(current-1)}>Previous sales</Button><span>Page {current+1} of {Math.max(1,Math.ceil(rows.length/25))}</span><Button disabled={(current+1)*25>=rows.length} onClick={()=>setPage(current+1)}>Next sales</Button></section>
 {data?.restoredHistory?.length>0&&<details className="setup-drawer"><summary>Restored historical sale reviews</summary><p>These reviews retain their original evidence in the planning backup. They do not close any current imported sale.</p>{data.restoredHistory.map(r=><p key={r.id}>{r.at} · {r.disposition} · {r.note}</p>)}</details>}
 <details className="setup-drawer"><summary>Optional saved trade drafts</summary><TradeDrafts store={store}/></details>
 <Dialog fullScreen={mobile} open={!!detail} onClose={()=>{if(!busy)setDetail(null);}} maxWidth="md" fullWidth aria-labelledby="sale-review-title"><div className="review-heading"><h2 id="sale-review-title">Review sale {e?.sale.symbol}</h2><Button disabled={busy} onClick={()=>setDetail(null)}>Back to tracking</Button></div><div className="review-content">{error&&<Alert severity="error">{error}</Alert>}{message&&<Alert severity="success">{message}</Alert>}{e&&<>
 <p>{e.sale.accountLabel} · {e.sale.date??'Date unknown'} · {e.sale.quantity??'Unknown'} shares · {e.sale.cashAmount??'Unknown'} {e.sale.currency} reported cash.</p><p>Source: {e.sale.source} · {e.sale.rowRef}. {e.sale.window&&`Review ${e.sale.window.start} through ${e.sale.window.end}, inclusive.`}</p>
 {e.warnings.map((w,i)=><p key={i}>{w}</p>)}
 <h3>Possible acquisitions ({e.acquisitions.length})</h3>{!e.acquisitions.length&&<p>No matching acquisitions found in supplied records. Missing history and unreviewed relationships still require attention.</p>}
 <div className="table-wrap"><table aria-label="Sale acquisition evidence"><thead><tr><th>Account</th><th>Record</th><th>Date / shares</th><th>Source</th></tr></thead><tbody>{e.acquisitions.map((r,i)=><tr key={i}><td>{r.accountLabel}<small>{r.accountType}</small></td><td>{r.symbol??'Unknown'} · {r.action}<small>{r.relation} · {r.kind}</small></td><td>{r.date??'Unknown'}<small>{r.quantity??'Unknown'}</small></td><td>{r.rowRef}<small>{r.reference}</small></td></tr>)}</tbody></table></div>
 <details><summary>{e.uncertainties.length} transfers, disposals or unclassified records</summary>{e.uncertainties.map((r,i)=><p key={i}>{r.accountLabel} · {r.symbol??'Unknown'} · {r.date??'Unknown'} · {r.action} · {r.rowRef}</p>)}</details>
 <h3>History coverage across listed accounts</h3>{e.coverage.map(c=><p key={c.accountId}>{c.label}: {c.status.replaceAll('_',' ')}{c.gaps.length>0&&` · missing ${c.gaps.map(g=>`${g.start}–${g.end}`).join(', ')}`}</p>)}
 <Alert severity="warning">Closing records your review only. An elapsed window, complete collection declaration or review closure does not mean wash-sale cleared.</Alert>
 <TextField select label="Sale review result" value={disposition} disabled={busy||!e.sale.active||e.sale.accountType!=='taxable'} onChange={ev=>{setDisposition(ev.target.value);setReviewed(false);}} fullWidth sx={{mt:2}}><MenuItem value="reviewed">Reviewed — keep tracking</MenuItem><MenuItem value="closed" disabled={e.sale.phase!=='window_elapsed'}>Close review — window elapsed</MenuItem></TextField>
 <TextField label="Sale review note" value={note} multiline fullWidth sx={{mt:2}} onChange={ev=>{setNote(ev.target.value);setReviewed(false);}} slotProps={{htmlInput:{maxLength:1000}}}/>
 <FormControlLabel control={<Checkbox checked={reviewed} onChange={ev=>setReviewed(ev.target.checked)}/>} label="I reviewed the sale, acquisition evidence and gaps; this is not tax clearance."/>
 <Button variant="contained" disabled={busy||!reviewed||note.trim().length<3||!e.sale.active||e.sale.accountType!=='taxable'} onClick={()=>run(async()=>{await store.replacements({action:'tracking-review',saleId:e.sale.id,hash:detail.hash,disposition,note,reviewed:true});await open(e.sale.id);await load();setMessage('Review saved. New evidence or a window milestone will require another review.');})}>Save sale review</Button><Button disabled={busy} onClick={()=>run(()=>open(e.sale.id))}>Reload sale evidence</Button>
 <details><summary>Review history ({detail.reviews.length})</summary>{detail.reviews.map(r=><p key={r.id}>{new Date(r.created_at).toLocaleString()} · {r.disposition} · {r.note}</p>)}</details>
 <p><a href="https://www.irs.gov/publications/p550" target="_blank" rel="noreferrer">IRS Publication 550</a> · Rule reference reviewed September 26, 2026.</p>
 </>}</div></Dialog></>;
}
