import React,{useEffect,useState} from 'react';
import {Alert,Button} from '@mui/material';
export default function TradeDrafts({store}:any){
 const [drafts,setDrafts]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(true);
 async function load(){setBusy(true);setError('');try{setDrafts((await store.replacements({action:'drafts'})).drafts);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[store]);
 function download(d){const url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`trade-draft-${d.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="card"><h1>Saved trade drafts</h1><Alert severity="info">These are historical, unexecuted plans. Review current holdings, prices and acquisition activity before acting. Imported sales are tracked separately above; drafts are not linked to executions. Alerts are not available yet.</Alert><Button disabled={busy} onClick={load}>Refresh drafts</Button>{busy&&<p role="status">Loading drafts…</p>}{error&&<Alert severity="error">{error}</Alert>}{!busy&&!error&&!drafts.length&&<p>No drafts yet. Open an opportunity, select lots, compare replacements and save your review.</p>}{drafts.map(d=><article className="card" key={d.id}><h2>{d.evidence.comparison.symbol} → {d.evidence.replacement.symbol}</h2><p>{d.evidence.account.label} · {d.evidence.selected.quantity} shares · ${d.evidence.selected.amount} · saved {new Date(d.saved_at).toLocaleString()}</p><p>{d.restored_from&&"Restored historical draft · original account and evidence shown · "}Needs fresh review before acting · price dated {d.evidence.price.date} · holdings revision {d.evidence.holdingsRevision}</p><details><summary>Saved draft evidence</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(d.evidence,null,2)}</pre></details><Button onClick={()=>download(d)}>Export draft evidence</Button></article>)}<p>Showing up to 100 most recent drafts. Individual evidence exports are reference copies. Use Recovery to export or restore a planning backup.</p></section>;
}
