import React,{useMemo,useState} from 'react';
import {Alert,Button,Dialog,DialogContent,DialogTitle,MenuItem,TextField} from '@mui/material';
import {buildValuation,prepareScenarioPrice,holdingKey,valuationSummary,combineValuationPrices} from './valuation/engine.mjs';
import QuotePanel from './QuotePanel';

const display=value=>{if(value===null||value===undefined)return 'Unknown';const [whole,fraction]=String(value).split('.');return whole.replace(/\B(?=(\d{3})+(?!\d))/g,',')+(fraction===undefined?'':`.${fraction}`);};
const local=value=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const utc=value=>value?new Date(value).toISOString():null;
const statuses={missing:'Missing',invalid:'Invalid',future:'After valuation time',stale:'Older than 15 min','time-unknown':'Time unknown',recent:'Within 15 min','daily-close':'Daily close'};
export default function Valuation({state,prices,onPrices,asOf,onAsOf,onRefresh,onReconcile,quoteRequest,providerResult,setProviderResult,priceMode,setPriceMode}:{state:any,prices:any[],onPrices:(p:any[])=>void,asOf:string,onAsOf:(v:string)=>void,onRefresh:()=>Promise<void>,onReconcile:()=>void,quoteRequest?:(body:any)=>Promise<any>,providerResult:any,setProviderResult:(v:any)=>void,priceMode:string,setPriceMode:(v:string)=>void}){
  const [account,setAccount]=useState(''),[symbol,setSymbol]=useState(''),[price,setPrice]=useState(''),[currency,setCurrency]=useState(''),[reference,setReference]=useState(''),[time,setTime]=useState('');
  const [filterAccount,setFilterAccount]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0),[detailKey,setDetailKey]=useState<string|null>(null);
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);
  const rows=useMemo(()=>buildValuation(state,combineValuationPrices(state,prices,providerResult.items,asOf,priceMode),asOf),[state,prices,asOf,providerResult,priceMode]);
  const visible=rows.filter(r=>(!filterAccount||r.accountId===filterAccount)&&r.symbol.toLowerCase().includes(search.toLowerCase()));
  const summary=valuationSummary(visible),detail=rows.find(r=>r.key===detailKey),pages=Math.max(1,Math.ceil(visible.length/25)),currentPage=Math.min(page,pages-1);
  function select(id,sym){setAccount(id);setSymbol(sym);const saved=prices.find(p=>p.accountId===id&&p.symbol===sym);setPrice(saved?.price??'');setCurrency(saved?.currency??'');setReference(saved?.reference??'');setTime(saved?.observedAt?local(saved.observedAt):'');setError('');}
  function apply(){setError('');try{const next=prepareScenarioPrice(state,{accountId:account,symbol,price,currency,reference,observedAt:utc(time)});onPrices([...prices.filter(p=>holdingKey(p.accountId,p.symbol)!==holdingKey(account,symbol)),next]);}catch(e:any){setError(e.message);}}
  return <>
    <Alert severity="info">{quoteRequest?'Valuation can use provider quotes with labelled scenario fallbacks. Choose Scenario only to test your own prices.':'Scenario valuation uses prices you enter here. Prices are not fetched or verified.'} Scenario prices stay in this open app session and clear on browser reload or sign-out. Accepted imports and corrections are unchanged.</Alert>
    {quoteRequest&&<><QuotePanel rows={rows} request={quoteRequest} onResult={setProviderResult} onRefreshTime={()=>onAsOf(new Date().toISOString())}/><TextField select label="Valuation price source" value={priceMode} onChange={e=>setPriceMode(e.target.value)} sx={{my:2,minWidth:300}}><MenuItem value="provider">Provider, then scenario fallback</MenuItem><MenuItem value="scenario">Scenario only</MenuItem></TextField></>}
    {error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}
    <section className="card"><h2>Valuation time and evidence</h2><div className="table-tools"><TextField type="datetime-local" label="Valuation time (local)" value={local(asOf)} slotProps={{inputLabel:{shrink:true}}} onChange={e=>{try{const value=utc(e.target.value);if(value)onAsOf(value);}catch{setError('Choose a valid valuation time.');}}}/><Button onClick={()=>onAsOf(new Date().toISOString())}>Use current time</Button><Button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await onRefresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Refresh holding evidence</Button></div><p>Price age and holding observation dates are shown separately. History coverage, holding periods, tax savings, and wash-sale screening are not assessed in this milestone.</p></section>
    <section className="card"><h2>Enter a scenario price</h2><div className="form-grid">
      <TextField select label="Price account" value={account} onChange={e=>select(e.target.value,'')}><MenuItem value="">Choose account</MenuItem>{state.accounts.map(a=><MenuItem key={a.id} value={a.id}>{a.portfolioName?`${a.portfolioName} / `:''}{a.label}</MenuItem>)}</TextField>
      <TextField select label="Price security" value={symbol} onChange={e=>select(account,e.target.value)}><MenuItem value="">Choose active security</MenuItem>{rows.filter(r=>r.accountId===account).map(r=><MenuItem key={r.symbol} value={r.symbol}>{r.symbol}</MenuItem>)}</TextField>
      <TextField label="Scenario price" value={price} onChange={e=>setPrice(e.target.value)} helperText="Nonnegative decimal. An explicit zero is allowed."/><TextField label="Price currency" value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())} helperText="Three-letter code, e.g. USD. No currency conversion."/>
      <TextField label="Price reference" value={reference} onChange={e=>setReference(e.target.value)} placeholder="e.g. Hypothetical test price"/><TextField type="datetime-local" label="Price time (local)" value={time} onChange={e=>setTime(e.target.value)} slotProps={{inputLabel:{shrink:true}}} helperText="Leave blank if unknown. Future-dated prices are excluded."/>
    </div><div className="section-end"><p>Prices apply only to this account and security.</p><Button variant="contained" disabled={!account||!symbol} onClick={apply}>Apply scenario price</Button></div><Button disabled={!prices.some(p=>p.accountId===account&&p.symbol===symbol)} onClick={()=>{onPrices(prices.filter(p=>p.accountId!==account||p.symbol!==symbol));select(account,symbol);}}>Remove selected price</Button><Button disabled={!prices.length} onClick={()=>onPrices([])}>Clear all scenario prices</Button></section>
    <section className="card"><h2>Position valuation</h2><div className="table-tools"><TextField select label="Valuation account filter" value={filterAccount} slotProps={{select:{displayEmpty:true},inputLabel:{shrink:true}}} onChange={e=>{setFilterAccount(e.target.value);setPage(0);}} sx={{minWidth:250}}><MenuItem value="">All accounts</MenuItem>{state.accounts.map(a=><MenuItem key={a.id} value={a.id}>{a.label}</MenuItem>)}</TextField><TextField label="Find valuation security" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/><span>{visible.length} active holdings</span></div>
      <p>Position and lot values describe the same holdings. Subtotals below use positions only. Unknown amounts are excluded and never treated as zero. Stale or undated scenario prices remain visible with warnings.</p>
      <div className="table-wrap"><table aria-label="Valuation subtotals"><thead><tr><th>Currency</th><th>Known market value</th><th>Valued positions</th><th>Known unrealized P/L</th><th>Positions with known P/L</th><th>With review flags</th></tr></thead><tbody>{summary.map(s=><tr key={s.currency}><td>{s.currency}</td><td>{display(s.marketValue)}</td><td>{s.valued} / {s.positions}</td><td>{display(s.pnl)}</td><td>{s.knownPnl} / {s.positions}</td><td>{s.review}</td></tr>)}</tbody></table></div>
      <div className="table-wrap"><table aria-label="Position valuations"><thead><tr><th>Security / account</th><th>Quantity / basis</th><th>Price / source / currency</th><th>Price age</th><th>Market value</th><th>Unrealized P/L</th><th>Review</th></tr></thead><tbody>{visible.slice(currentPage*25,(currentPage+1)*25).map(r=><tr key={r.key}><td><strong>{r.symbol}</strong><small>{r.accountLabel} · {r.accountType}</small></td><td>{display(r.quantity)}<small>Basis {display(r.basis)} {r.currency??''}</small></td><td>{display(r.price?.price)}<small>{r.price?.currency??'Unknown'} · {r.price?.kind==='provider'?(r.price.provider==='massive'?'Massive daily close':'Twelve Data'):r.price?.fallbackReason?'Scenario fallback':r.price?'Scenario':'No price'}</small></td><td>{statuses[r.priceStatus]}</td><td>{display(r.marketValue)}</td><td>{display(r.pnl)}</td><td><Button aria-label={`Inspect valuation ${r.accountLabel} ${r.symbol}`} onClick={()=>setDetailKey(r.key)}>Lots & evidence{r.reasons.length+r.issues.length?` (${r.reasons.length+r.issues.length})`:''}</Button><Button aria-label={`Set price ${r.accountLabel} ${r.symbol}`} onClick={()=>select(r.accountId,r.symbol)}>Set price</Button></td></tr>)}</tbody></table></div>
      {!visible.length&&<p>No active holdings match this view.</p>}<div className="pagination"><span>Page {currentPage+1} of {pages}</span><Button disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>Previous valuations</Button><Button disabled={currentPage+1>=pages} onClick={()=>setPage(currentPage+1)}>Next valuations</Button></div>
    </section>
    <Dialog open={Boolean(detail)} onClose={()=>setDetailKey(null)} fullWidth maxWidth="lg"><DialogTitle>{detail?.symbol} · {detail?.price?.kind==='provider'?'provider':'scenario'} valuation<Button style={{float:'right'}} onClick={()=>setDetailKey(null)}>Close valuation</Button></DialogTitle><DialogContent>{detail&&<>
      <p>{detail.portfolioName?`${detail.portfolioName} / `:''}{detail.accountLabel} · {detail.accountType}. P/L is a valuation calculation, not a harvesting recommendation.</p>
      <p>Position effective: {detail.positionDate??'Unknown'} · lots effective: {detail.lotDate??'Unknown'} · lot coverage: {detail.lotCoverage}.</p><p>Price: {display(detail.price?.price)} {detail.price?.currency??''} · time: {detail.price?.observedAt??'Unknown'} · reference: {detail.price?.reference??'None'}.</p>
      {detail.price?.kind==='provider'&&<p>Retrieved: {detail.price.fetchedAt}. Source: {detail.price.provider==='massive'?'Massive daily close':'Twelve Data'} / {detail.price.providerSymbol} / {detail.price.priceDate??detail.price.mic}.</p>}
      {detail.reasons.map((reason,i)=><Alert key={i} severity="warning" sx={{mb:1}}>{reason}</Alert>)}{detail.issues.map((issue,i)=><p key={i}>{issue.category}: {issue.title}</p>)}
      {detail.corrections.length>0&&<Alert severity="info">This view includes {detail.corrections.filter(c=>c.status==='active').length} applied corrections; {detail.corrections.filter(c=>c.status==='conflict').length} corrections are suspended. Original sources remain in History.</Alert>}
      <Button onClick={()=>{setDetailKey(null);onReconcile();}}>Open reconciliation</Button>
      <h3>Individual lot valuations</h3><p>Each observed row remains separate. These values are not added to the position subtotal.</p>{detail.lots.length?<div className="table-wrap" style={{maxHeight:420,overflow:'auto'}}><table aria-label="Lot valuations"><thead><tr><th>Row / source reference</th><th>Acquired</th><th>Quantity</th><th>Basis</th><th>Currency</th><th>Market value</th><th>Unrealized P/L</th><th>Price / amount warnings</th></tr></thead><tbody>{detail.lots.map(l=><tr key={l.index}><td>{l.index+1} / {l.row_ref??'Unknown'}</td><td>{l.acquisition_date??'Unknown'}</td><td>{display(l.quantity)}</td><td>{display(l.total_basis)}</td><td>{l.currency??'Unknown'}</td><td>{display(l.marketValue)}</td><td>{display(l.pnl)}</td><td>{l.reasons.join('; ')||'—'}</td></tr>)}</tbody></table></div>:<p>No accepted complete lot snapshot. No individual lots are inferred from the position.</p>}
    </>}</DialogContent></Dialog>
  </>;
}
