import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite(),a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
async function role(name,user=a){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.exec(`set role ${name}`);}
const rpc=async(sql,args)=>(await db.query(sql,args)).rows[0].value;
const read=()=>rpc('select read_activity($1) as value',[a]);
async function prepare(){const saved=await read();return rpc('select prepare_activity($1,$2) as value',[a,JSON.stringify({baseRevision:saved.revision,accounts:saved.accounts,kind:'batch',reason:'Synthetic SQL validation',after:{version:1,events:[...saved.state.events,{id:crypto.randomUUID(),kind:'batch',actor:'forged',at:'fake'}]}})]);}
const commit=id=>rpc('select commit_activity($1,$2) as value',[a,id]);
let first;
before(async()=>{await db.exec(`create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to anon,authenticated,service_role;create table public.accounts(id uuid primary key,user_id uuid,label text);grant all on accounts to service_role;create function public.analysis_input_accounts(p_user uuid) returns jsonb language sql stable as $$select coalesce(jsonb_agg(to_jsonb(a) order by id),'[]'::jsonb) from public.accounts a where user_id=p_user$$;`);await db.query('insert into auth.users values($1),($2)',[a,b]);await db.query("insert into accounts values($1,$1,'Synthetic')",[a]);await db.exec(await readFile(new URL('../../supabase/migrations/202609170001_activity.sql',import.meta.url),'utf8'));await role('service_role');});
after(()=>db.close());
test('activity prepare is non-mutating and acceptance stamps actor/time with an idempotent receipt',async()=>{first=await prepare();assert.equal((await read()).revision,0);const result=await commit(first);assert.deepEqual(await commit(first),result);const saved=await read();assert.equal(saved.revision,1);assert.equal(saved.audit.length,1);assert.equal(saved.state.events[0].actor,a);assert(Number.isFinite(Date.parse(saved.state.events[0].at)));});
test('owner RLS protects sources and audits, and clients cannot write or call privileged activity RPCs',async()=>{await role('authenticated',b);assert.deepEqual((await db.query('select * from activity_state')).rows,[]);assert.deepEqual((await db.query('select * from activity_audit')).rows,[]);await assert.rejects(db.query('select * from prepared_activity'),/permission denied/);await assert.rejects(db.query('select read_activity($1)',[a]),/permission denied/);await role('authenticated',a);assert.equal((await db.query('select * from activity_state')).rows.length,1);for(const sql of ['delete from activity_audit','update activity_state set revision=99',`select commit_activity('${a}','${first}')`])await assert.rejects(db.query(sql),/permission denied/);await role('anon');await assert.rejects(db.query('select * from activity_state'),/permission denied/);});
test('foreign prepared IDs, stale revisions, changed account inventories and expiration cannot commit',async()=>{await role('service_role');const old=await prepare(),next=await prepare();await assert.rejects(rpc('select commit_activity($1,$2) as value',[b,next]),/unavailable/);await commit(next);await assert.rejects(commit(old),/stale/);const renamed=await prepare();await db.query("update accounts set label='Renamed' where id=$1",[a]);await assert.rejects(commit(renamed),/inventory/);const expired=await prepare();await db.query("update prepared_activity set created_at=now()-interval '25 hours' where id=$1",[expired]);await assert.rejects(commit(expired),/expired/);assert.equal((await read()).revision,2);});
test('failure after audit insertion rolls back the entire acceptance and the same review can retry',async()=>{await role('service_role');const id=await prepare(),before=await read();await db.exec('reset role');await db.exec(`create function fail_activity_test() returns trigger language plpgsql as $$begin raise exception 'synthetic rollback';end$$;create trigger fail_activity_test before update on public.activity_state for each row execute function fail_activity_test();`);await role('service_role');await assert.rejects(commit(id),/synthetic rollback/);assert.deepEqual(await read(),before);await db.exec('reset role');await db.exec('drop trigger fail_activity_test on public.activity_state;drop function fail_activity_test();');await role('service_role');assert.equal((await commit(id)).revision,3);});
