import {test} from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {readFile,readdir} from 'node:fs/promises';
test('deletion migration with full schema: ownership, stale preview, write freeze, files-first, retry and reset',async()=>{
 const db=new PGlite();const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,unique(bucket_id,name));grant usage on schema public,auth,storage to anon,authenticated,service_role;`);
 const dir=new URL('../../supabase/migrations/',import.meta.url);for(const f of (await readdir(dir)).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile(new URL(f,dir),'utf8'));
 const owned=(await db.query("select table_name from information_schema.columns where table_schema='public' and column_name='user_id' and table_name not in ('data_deletions','api_request_usage','upload_daily_usage')")).rows.map(r=>r.table_name).sort();const declared=(await db.query('select financial_tables() names')).rows[0].names.sort();assert.deepEqual(declared,owned);
 await db.query('insert into auth.users values($1),($2)',[a,b]);await db.query("insert into portfolios(id,user_id,name) values($1,$1,'Synthetic'),($2,$2,'Other user')",[a,b]);await db.query("insert into accounts(id,user_id,portfolio_id,label,broker) values($1,$1,$1,'Synthetic','schwab')",[a]);
 const rpc=async(name,args)=>(await db.query(`select ${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
 let plan=await rpc('prepare_data_deletion',[a]);assert.equal(plan.summary.accounts,1);await db.query("update accounts set label='Changed' where id=$1",[a]);await assert.rejects(rpc('begin_data_deletion',[a,plan.token]),/Data changed/);
 const path=a+'/synthetic/source';await db.query("insert into import_sources(user_id,path,name,hash,bytes) values($1,$2,'synthetic.json',$3,2)",[a,path,'a'.repeat(64)]);await db.query("insert into storage.objects(bucket_id,name) values('import-sources',$1)",[path]);
 plan=await rpc('prepare_data_deletion',[a]);await assert.rejects(rpc('begin_data_deletion',[b,plan.token]),/unavailable/);
 await db.exec('set role authenticated');await assert.rejects(rpc('begin_data_deletion',[a,plan.token]),/permission denied/);await db.exec('reset role');
 const job=await rpc('begin_data_deletion',[a,plan.token]);assert.deepEqual(job.paths,[path]);await assert.rejects(db.query("update accounts set label='Forged' where id=$1",[a]),/deletion/);await assert.rejects(rpc('finish_data_deletion',[a,plan.token]),/Original files remain/);await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values('import-sources',$1) on conflict(bucket_id,name) do update set name=excluded.name",[path]),/Uploads disabled/);
 await db.query('delete from storage.objects where name=$1',[path]);assert.equal((await rpc('finish_data_deletion',[a,plan.token])).status,'complete');assert.equal((await rpc('finish_data_deletion',[a,plan.token])).status,'complete');assert.equal((await db.query('select count(*)::int n from portfolios where user_id=$1',[a])).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from portfolios where user_id=$1',[b])).rows[0].n,1);
 await assert.rejects(db.query("insert into portfolios(user_id,name) values($1,'late write')",[a]),/deletion/);await rpc('reopen_financial_workspace',[a]);await db.query("insert into portfolios(user_id,name) values($1,'Empty restart')",[a]);
 }finally{await db.close();}
});
