import test from 'node:test';import assert from 'node:assert/strict';import {reconcileRealized} from '../src/realized/reconciliation.mjs';
const lot={symbol:'ABC',closed:'2026-09-23',opened:'2025-01-01',quantity:'0.1',proceeds:'10.01',row:3};
const reports=[{id:'r',account_id:'a',active:true,name:'details.csv',document:{start:'2026-01-01',end:'2026-09-30',rows:[lot,{...lot,row:4,quantity:'0.2',proceeds:'20.02'}]}}];
const sale={id:'s',action:'sell',symbol:'ABC',date:'2026-09-23',quantity:'0.3',cashAmount:'30.03',currency:'USD',rowRef:'sale'};
const activity=(rows=[sale],status='complete')=>({events:[{kind:'batch',id:'b',accountId:'a',document:{reference:'Synthetic',coverage:{start:'2026-09-23',end:'2026-09-23',status},rows},transactions:rows}]});
const run=(rs=reports,a=activity(),accounts=[{id:'a'}])=>reconcileRealized(rs,a,accounts,'2026');
test('daily reconciliation uses exact sums and preserves all lot evidence',()=>{const [r]=run();assert.equal(r.status,'Totals match');assert.equal(r.quantityDifference,'0');assert.equal(r.proceedsDifference,'0');assert.equal(r.lots.length,2);assert.equal(run(reports,activity(),[{id:'other'}]).length,0);});
test('differences and unknown amounts remain unresolved',()=>{assert.equal(run(reports,activity([{...sale,quantity:'0.2'}]))[0].status,'Quantity difference');assert.equal(run(reports,activity([{...sale,cashAmount:'30.02'}]))[0].proceedsDifference,'0.01');for(const change of [{quantity:null},{currency:'CAD'},{cashAmount:null}])assert.equal(run(reports,activity([{...sale,...change}]))[0].status,'Incomplete sale amounts');assert.ok(run(reports,activity([{...sale,date:null}])).some(r=>r.status==='Incomplete sale identity'));});
test('coverage separates missing evidence from missing records; retired sources excluded',()=>{assert.equal(run(reports,activity([]))[0].status,'Missing sale');assert.equal(run(reports,activity([],'partial'))[0].status,'Activity coverage needed');assert.equal(run([],activity())[0].status,'Realized report coverage needed');assert.equal(run([{...reports[0],document:{...reports[0].document,rows:[]}}])[0].status,'Missing realized lots');assert.equal(run([{...reports[0],active:false}])[0].status,'Realized report coverage needed');const a=activity();a.events.push({kind:'withdraw',batchId:'b'});assert.equal(run(reports,a)[0].status,'Activity coverage needed');});
