import test from 'node:test';import assert from 'node:assert/strict';
import {saleInventory,saleEvidence} from '../src/analysis/sale-tracking.mjs';
const accounts=[{id:'tax',label:'Taxable',type:'taxable'},{id:'ira',label:'IRA',type:'roth_ira'}];
const batch=(id,accountId,transactions,dependencies=[])=>({kind:'batch',id,accountId,transactions,dependencies,source:{name:id},document:{reference:id,rows:transactions,coverage:{start:'2026-08-01',end:'2026-10-31',status:'complete'}}});
const row=(id,date,action,symbol='GOOG')=>({id,date,action,symbol,quantity:'0.5',currency:'USD',rowRef:id});
const holdings={holdings:{},corrections:[]};
test('inclusive calendar window stays open on day 30 and separate partial sales remain separate',()=>{const a={events:[batch('a','tax',[row('s','2026-09-01','sell'),row('s2','2026-09-01','sell')])]};assert.equal(saleInventory(a,accounts,'2026-10-01').length,2);assert.equal(saleInventory(a,accounts,'2026-10-01')[0].phase,'window_open');assert.equal(saleInventory(a,accounts,'2026-10-02')[0].phase,'window_elapsed');assert.deepEqual(saleInventory(a,accounts,'2026-10-02')[0].window,{start:'2026-08-02',end:'2026-10-01'});});
test('same-day, boundary, IRA reinvestment and known share class evidence are retained without quantity matching',()=>{const a={events:[batch('a','tax',[row('s','2026-09-01','sell')]),batch('b','ira',[row('b1','2026-08-02','buy'),row('b2','2026-09-01','reinvest','GOOGL'),row('b3','2026-10-01','buy'),row('out','2026-10-02','buy'),row('uncertain',null,'transfer_in')])]};const sale=saleInventory(a,accounts,'2026-10-02')[0],before=structuredClone(a),r=saleEvidence({sale,activity:a,holdings,accounts,today:'2026-10-02'});assert.equal(r.acquisitions.length,3);assert.equal(r.acquisitions[1].relation,'known related share class');assert.equal(r.uncertainties.length,1);assert.equal(r.coverage[1].status,'uncertain_records');assert.deepEqual(a,before);assert.equal(r.matchedQuantity,undefined);});
test('withdrawn and dependent suspended sources remain historical and stop contributing acquisitions',()=>{const a={events:[batch('a','tax',[row('s','2026-09-01','sell')]),batch('b','ira',[row('b','2026-09-02','buy')],['a']),{kind:'withdraw',batchId:'a'}]};const sale=saleInventory(a,accounts,'2026-10-02')[0];assert.equal(sale.sourceStatus,'withdrawn');assert.equal(sale.active,false);assert.equal(saleEvidence({sale,activity:a,holdings,accounts,today:'2026-10-02'}).acquisitions.length,0);});

test('missing and future sale dates stay explicit and cannot masquerade as elapsed windows',()=>{const a={events:[batch('a','tax',[row('missing',null,'sell'),row('future','2027-01-01','sell')])]};const rows=saleInventory(a,accounts,'2026-09-26');assert.equal(rows.find(s=>s.id==='missing').phase,'date_missing');assert.equal(rows.find(s=>s.id==='future').phase,'future_sale');});
