import React,{useState} from 'react';
import {Alert,Button,Checkbox,FormControlLabel,TextField} from '@mui/material';
import type {SupabaseClient} from '@supabase/supabase-js';
import {supabaseStore} from '../import/supabase-store';
export default function DataPrivacy({client,email,onDeleted}:{client:SupabaseClient;email:string;onDeleted:()=>void}){
 const [plan,setPlan]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[reviewed,setReviewed]=useState(false),[message,setMessage]=useState('');
 const store=supabaseStore(client);
 async function call(body:any){const {data,error}=await client.functions.invoke('imports',{body});if(error){let text='Data privacy service is unavailable. Retry to check the status.';try{text=(await error.context.json()).error||text;}catch{}throw new Error(text);}return data;}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);setPassword('');}}
 function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function backup(kind:string){let text;if(kind==='holdings')text=await store.exportBackup();else{const result=kind==='activity'?await store.activity({action:'export'}):kind==='analysis'?await store.analysis({action:'export'}):await store.replacements({action:kind==='planning'?'planning-export':'realized-backup'});text=JSON.stringify(result.backup,null,2);}download(`tlh-${kind}-backup.json`,text);setMessage('Backup downloaded. Keep it in encrypted storage; it contains private financial information.');}
 async function authenticate(){const {error}=await client.auth.signInWithPassword({email,password});if(error)throw new Error('Password confirmation failed.');}
 return <section className="card"><h2>Data privacy & recovery</h2><p>Download backups before deleting data. Holdings backups include accepted original files; staged uploads must be saved separately. Restore each backup through its matching Recovery, Transactions, Analysis inputs, or Realized reports view.</p>
 <div className="section-end">{['holdings','activity','analysis','planning','realized'].map(kind=><Button key={kind} disabled={busy||plan?.status==='deleting'||plan?.status==='complete'} onClick={()=>run(()=>backup(kind))}>Back up {kind}</Button>)}</div>
 <p className="muted">Platform database backups do not include uploaded files. Copies you download and provider backups are not erased by this action; provider retention applies. This action keeps your sign-in and operational abuse-limit counters.</p>
 {error&&<Alert severity="error">{error}</Alert>}{message&&<Alert severity="info">{message}</Alert>}
 <Button color="error" disabled={busy} onClick={()=>run(async()=>{setPlan(await call({action:'data-preview'}));setReviewed(false);setConfirmation('');})}>Review deletion of all financial data</Button>
 {plan&&plan.status!=='complete'&&<><Alert severity="warning">This deletes ALL your portfolios, brokerage accounts, holdings, transactions, realized reports, planning evidence, alerts, history, and original uploaded files. It cannot be undone without your own backups. Other users are unaffected.</Alert>
 {plan.status==='deleting'?<p>Deletion is unfinished. New writes are blocked. Retry to finish removing files and records.</p>:<p>{plan.summary.accounts||0} accounts · {plan.summary.current_holdings||0} holdings · {plan.summary.import_sources||0} uploaded originals · {plan.summary.realized_reports||0} realized reports</p>}
 <FormControlLabel control={<Checkbox checked={reviewed} disabled={busy} onChange={e=>setReviewed(e.target.checked)}/>} label="I have saved the backups I need and understand all my financial data will be deleted."/>
 <TextField label="Type DELETE MY DATA" value={confirmation} disabled={busy} onChange={e=>setConfirmation(e.target.value)}/><TextField type="password" autoComplete="current-password" label="Confirm password" value={password} disabled={busy} onChange={e=>setPassword(e.target.value)}/>
 <Button color="error" variant="contained" disabled={busy||!reviewed||confirmation!=='DELETE MY DATA'||!password} onClick={()=>run(async()=>{await authenticate();const result=await call({action:'data-delete',token:plan.token,confirmation,reviewed});setPlan(result);onDeleted();setConfirmation('');setMessage('Financial data and uploaded originals deleted. Close other open app tabs before starting again.');})}>{plan.status==='deleting'?'Retry deletion':'Permanently delete my financial data'}</Button></>}
 {plan?.status==='complete'&&<><Alert severity="success">Your financial workspace is empty. Your sign-in remains available.</Alert><p>Close other app tabs. To create accounts again, type START EMPTY and confirm your password.</p><TextField label="Type START EMPTY" value={confirmation} onChange={e=>setConfirmation(e.target.value)} disabled={busy}/><TextField type="password" label="Confirm password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/><Button disabled={busy||confirmation!=='START EMPTY'||!password} onClick={()=>run(async()=>{await authenticate();await call({action:'data-reopen',confirmation});location.reload();})}>Start empty workspace</Button></>}
 </section>;
}
