import {test,expect} from '@playwright/test';
test('public demo and onboarding stay isolated and provide an honest local handoff',async({page})=>{
 const remote=[];page.on('request',r=>{if(/functions\/v1|auth\/v1|rest\/v1/.test(r.url()))remote.push(r.url());});
 await page.goto('/');await expect(page.getByRole('heading',{name:/Your portfolio/})).toBeVisible();await page.screenshot({path:'test-results/landing-page.png',fullPage:true});
 await page.getByRole('link',{name:'Explore the demo →'}).click();await expect(page.getByRole('table',{name:'Synthetic opportunities'}).getByRole('row')).toHaveCount(4);
 await expect(page.getByRole('table',{name:'Synthetic opportunities'})).toContainText('NOVA → ORBT');await expect(page.getByRole('table',{name:'Synthetic opportunities'})).toContainText('Same sector: Enterprise software');await expect(page.getByRole('table',{name:'Synthetic opportunities'})).toContainText('recent purchase requiring review');
 await page.getByLabel('Holding-period evidence').selectOption('Long term');await expect(page.getByRole('table')).toContainText('CEDR');await expect(page.getByRole('table')).not.toContainText('NOVA');await page.getByRole('button',{name:'Review CEDR'}).click();await page.getByRole('button',{name:'Explore replacement'}).click();await expect(page.getByRole('region',{name:'Review CEDR'})).toContainText('PINE');await page.getByRole('button',{name:'Review example'}).click();await page.getByLabel('I understand this is a fictional example.').check();await expect(page.getByRole('status')).toContainText('No order');
 await page.getByRole('link',{name:'Prepare my own portfolio →'}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Positions CSV',{exact:true}).check();await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('button',{name:'Download onboarding plan'})).toBeDisabled();await page.getByLabel('I understand that imports require review and this tool does not place trades.').check();
 const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Download onboarding plan'}).click();expect((await downloaded).suggestedFilename()).toBe('tlh-onboarding-plan.json');await expect(page.getByRole('link',{name:'Continue to account setup →'})).toHaveAttribute('href','/?workspace=accounts');expect(remote).toEqual([]);
 await page.getByRole('button',{name:'Back',exact:true}).click();await page.getByRole('button',{name:'Back',exact:true}).click();await page.getByRole('combobox',{name:'Broker',exact:true}).selectOption('Another broker');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('link',{name:'Continue to account setup →'})).not.toBeVisible();
 await page.setViewportSize({width:390,height:844});for(const route of ['home','demo','onboarding']){await page.goto('/?page='+route);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
});

