import {test,expect} from '@playwright/test';
import {sampleFiles} from '../../src/sample.mjs';
import {readSource} from '../../src/import/sources.mjs';
import {emptyState,previewImport,acceptPreview} from '../../src/import/engine.mjs';
async function fixture(){const state=emptyState(),plan=await previewImport(state,await Promise.all(sampleFiles().map(readSource)),{accountId:null,accountLabel:'Valuation test',accountType:'taxable',currency:'USD',sourceAccountRef:'synthetic-account',completeAccount:false});return acceptPreview(state,plan,{symbols:plan.rows.map(r=>r.symbol),includeCash:true,mappingReviewed:true,timingReviewed:true,reason:'Synthetic.'}).state;}
async function seed(page,state){await page.goto('/?workspace=pilot');await page.evaluate(state=>new Promise(resolve=>{const r=indexedDB.open('tlh-import-pilot-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('portfolio');r.onsuccess=()=>{const db=r.result,tx=db.transaction('portfolio','readwrite');tx.objectStore('portfolio').put(state,'current');tx.oncomplete=()=>{db.close();resolve();};};}),state);await page.reload();await page.getByRole('button',{name:'Prices',exact:true}).click();}
const persisted=page=>page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('tlh-import-pilot-v1',1);r.onsuccess=()=>{const db=r.result,q=db.transaction('portfolio').objectStore('portfolio').get('current');q.onsuccess=()=>{resolve(q.result);db.close();};};}));
test('scenario price values positions and separate lots; navigation retains prices, reload clears them without writing evidence',async({page})=>{
  const state=await fixture();await seed(page,state);await expect(page.getByRole('table',{name:'Position valuations'})).toContainText('Missing');
  await page.getByRole('button',{name:'Set price Valuation test EXAMPLE',exact:true}).click();await page.getByLabel('Scenario price',{exact:true}).fill('90');await page.getByLabel('Price currency',{exact:true}).fill('USD');await page.getByLabel('Price reference',{exact:true}).fill('Hypothetical validation price');await page.getByRole('button',{name:'Apply scenario price',exact:true}).click();
  const table=page.getByRole('table',{name:'Position valuations'}),row=table.getByRole('row').filter({hasText:'EXAMPLE'});await expect(row).toContainText('-20');await expect(row).toContainText('Time unknown');await expect(page.getByRole('table',{name:'Valuation subtotals'})).toContainText('1 / 3');
  await page.getByRole('button',{name:'Inspect valuation Valuation test EXAMPLE',exact:true}).click();await expect(page.getByRole('table',{name:'Lot valuations'}).locator('tbody tr')).toHaveCount(2);await expect(page.getByRole('dialog')).toContainText('Hypothetical validation price');await expect(page.getByRole('dialog')).toContainText('Lot effective date is unknown');
  await page.screenshot({path:'test-results/valuation-lots.png',fullPage:true,animations:'disabled'});await page.getByRole('button',{name:'Close valuation'}).click();
  await page.getByRole('button',{name:'Holdings',exact:true}).click();await page.getByRole('button',{name:'Prices',exact:true}).click();await expect(row).toContainText('-20');await page.getByRole('button',{name:'Refresh holding evidence'}).click();expect(await persisted(page)).toEqual(state);
  await page.screenshot({path:'test-results/valuation-dashboard.png',fullPage:true,animations:'disabled'});
  await page.reload();await page.getByRole('button',{name:'Prices',exact:true}).click();await expect(row).toContainText('Missing');await expect(row).not.toContainText('-20');expect(await persisted(page)).toEqual(state);
});
test('currency mismatch, explicit zero, price removal, filters and evidence navigation are visible',async({page})=>{
  const state=await fixture();await seed(page,state);await page.getByRole('button',{name:'Set price Valuation test EXAMPLE',exact:true}).click();
  await page.getByLabel('Scenario price',{exact:true}).fill('0');await page.getByLabel('Price currency',{exact:true}).fill('EUR');await page.getByLabel('Price reference',{exact:true}).fill('Synthetic mismatch');await page.getByRole('button',{name:'Apply scenario price',exact:true}).click();
  await page.getByRole('button',{name:'Inspect valuation Valuation test EXAMPLE',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Price and evidence currencies differ');await page.getByRole('button',{name:'Close valuation'}).click();
  await page.getByLabel('Price currency',{exact:true}).fill('USD');await page.getByRole('button',{name:'Apply scenario price',exact:true}).click();const row=page.getByRole('table',{name:'Position valuations'}).getByRole('row').filter({hasText:'EXAMPLE'});await expect(row).toContainText('-200');
  await page.getByLabel('Find valuation security',{exact:true}).fill('EXAMPLE');await expect(page.getByRole('table',{name:'Position valuations'}).locator('tbody tr')).toHaveCount(1);
  await page.getByRole('button',{name:'Remove selected price'}).click();await expect(row).toContainText('Missing');await page.getByRole('button',{name:'Inspect valuation Valuation test EXAMPLE',exact:true}).click();await page.getByRole('button',{name:'Open reconciliation',exact:true}).click();await expect(page.getByRole('heading',{name:'Reconciliation inbox'})).toBeVisible();expect(await persisted(page)).toEqual(state);
});
