import {ReviewError} from '../src/review-error.mjs';
const reviewMessages=new Set([
  "Account classification changed",
  "Account classification changed. Refresh the preview.",
  "Account inventory changed",
  "Activity changed. Check again.",
  "Alert changed or unavailable. Reload first.",
  "Alert inbox limit exceeded; scan was not saved.",
  "Alert limit exceeded",
  "Alert preferences changed. Check again.",
  "Alert preferences changed. Reload first.",
  "Backup upload unavailable",
  "Backup upload was discarded",
  "Choose an owned taxable account",
  "Choose owned taxable accounts",
  "Correction preview expired",
  "Correction preview is stale",
  "Correction preview unavailable",
  "Destination account changed",
  "Destination history changed. Restore into empty accounts.",
  "Destination must be empty",
  "Destination portfolio unavailable",
  "Destination strategy conflict",
  "Draft destination conflict",
  "Evidence changed. Refresh tracking.",
  "Holding unavailable",
  "Holdings changed. Check again.",
  "Invalid correction owner",
  "Invalid exclusions",
  "Invalid quote key",
  "Invalid target account",
  "New report must cover the full range of replaced reports",
  "Overlap changed. Preview again.",
  "Portfolio unavailable",
  "Preview expired. Build it again.",
  "Preview unavailable",
  "Provide a withdrawal reason",
  "Report history limit exceeded",
  "Report history limit reached",
  "Reports changed. Preview again.",
  "Restore preview expired",
  "Restore preview unavailable",
  "Review expired",
  "Review is stale",
  "Review unavailable",
  "Schedule changed. Reload first.",
  "Stale destination strategy",
  "Stale strategy",
  "Target account unavailable",
  "This preview is stale. Refresh it before accepting.",
  "This report was retired. Use a new corrected broker export.",
  "This restore preview is stale. Build it again.",
  "Tracking review limit reached",
  "Universe unavailable",
  "Unknown alert action",
  "Upload is no longer available",
  "Uploads were discarded. Build a new preview."
]);
export function databaseError(error){return new ReviewError(error?.code==='P0001' && reviewMessages.has(error.message)?error.message:'Database operation failed. Reload to check the result before retrying.');}
