import {test,expect} from '@playwright/test';
import {createClient} from '@supabase/supabase-js';
import {execFileSync} from 'node:child_process';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {localSupabase} from '../../scripts/configure-local-supabase.mjs';
import {supabaseStore} from '../../src/import/supabase-store.ts';
import {sampleFiles} from '../../src/sample.mjs';
import {readSource} from '../../src/import/sources.mjs';
import {activityView,activityCoverage,activityTemplate} from '../../src/activity/engine.mjs';
const good=async request=>{const {data,error}=await request;if(error)throw new Error(error.message);return data;};
test('manual and JSON activity preserve duplicates, review overlaps, persist privately and restore evidence without changing holdings',async({page})=>{
  const config=localSupabase(),password=`Synthetic-${randomUUID()}-Aa7!`,raw=JSON.parse(execFileSync(process.platform==='win32'?'supabase.exe':'supabase',['status','-o','json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));
  const admin=createClient(config.url,raw.SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}),people=[];
  for(let n=0;n<3;n++){
    const user=(await good(admin.auth.admin.createUser({email:`activity-${randomUUID().slice(0,8)}@example.test`,password,email_confirm:true}))).user;
    const client=createClient(config.url,config.key,{auth:{persistSession:false,autoRefreshToken:false}});await good(client.auth.signInWithPassword({email:user.email,password}));
    const portfolio=await good(client.from('portfolios').insert({user_id:user.id,name:`Activity validation ${n+1}`}).select().single());const account=await good(client.from('accounts').insert({user_id:user.id,portfolio_id:portfolio.id,label:'Activity test',broker:'schwab',account_type:'taxable'}).select().single());people.push({user,client,account,store:supabaseStore(client)});
  }
  const [a,b,c]=people;
  try{
    const importPlan=await a.store.buildPreview(await a.store.readState(),await Promise.all(sampleFiles().map(readSource)),{accountId:a.account.id,currency:'USD',sourceAccountRef:'synthetic-account',completeAccount:false});await a.store.commitImport(importPlan,{symbols:importPlan.rows.map(r=>r.symbol),includeCash:true,mappingReviewed:true,timingReviewed:true,reason:'Synthetic activity baseline.'});const holdings=await a.store.readState();
    await page.goto('/?workspace=imports');await page.getByRole('textbox',{name:'Email',exact:true}).fill(a.user.email);await page.getByLabel(/^Password/).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Transactions',exact:true}).click();
    await page.getByLabel('Activity account',{exact:true}).click();await page.getByRole('option',{name:'Activity validation 1 / Activity test',exact:true}).click();await page.getByLabel('Source account label',{exact:true}).fill('Synthetic source account');await page.getByLabel('Activity source reference',{exact:true}).fill('Synthetic September statement');await page.getByLabel('Activity entry reason',{exact:true}).fill('Validate manual transcription');await page.getByLabel('Source range start').fill('2026-09-01');await page.getByLabel('Source range end').fill('2026-09-17');await page.getByLabel('Activity collection coverage').click();await page.getByRole('option',{name:'All account activity in this range — my declaration',exact:true}).click();
    for(let i=0;i<2;i++){await page.getByLabel('Activity trade date').fill('2026-09-10');await page.getByLabel('Activity symbol',{exact:true}).fill('EXAMPLE');await page.getByLabel('Activity quantity',{exact:true}).fill('1.25');await page.getByLabel('Reported cash amount').fill('-125');await page.getByLabel('Activity currency',{exact:true}).fill('USD');await page.getByRole('button',{name:'Add activity row'}).click();}
    await page.getByRole('button',{name:'Preview activity',exact:true}).click();await expect(page.getByRole('table',{name:'Activity review'})).toContainText('row-2');expect((await a.store.activity({action:'read'})).revision).toBe(0);await expect(page.getByRole('button',{name:'Accept activity review'})).toBeDisabled();
    await page.getByLabel('I reviewed the account, original source, overlap choices and collection coverage.').check();await page.getByRole('button',{name:'Accept activity review'}).click();await expect(page.getByText('Activity saved at revision 1. Holdings and lot evidence are unchanged.')).toBeVisible();
    const first=await a.store.activity({action:'read'});expect(activityView(first.state).transactions).toHaveLength(2);expect(first.state.events[0].actor).toBe(a.user.id);
    await page.reload();await page.getByRole('button',{name:'Transactions',exact:true}).click();await expect(page.getByText(/2 active records/)).toBeVisible();await page.getByLabel('Coverage check start').fill('2026-09-01');await page.getByLabel('Coverage check end').fill('2026-09-17');await page.getByRole('button',{name:'Check supplied coverage'}).click();await expect(page.getByRole('table',{name:'Activity coverage'})).toContainText('covered in supplied records');
    expect(await good(b.client.from('activity_state').select('*'))).toEqual([]);expect(await good(b.client.from('activity_audit').select('*'))).toEqual([]);expect((await a.client.from('activity_state').update({revision:999}).eq('user_id',a.user.id)).error).toBeTruthy();expect((await a.client.rpc('read_activity',{p_user:a.user.id})).error).toBeTruthy();
    const original=first.state.events[0].document;await expect(b.store.activity({action:'prepare',accountId:a.account.id,baseRevision:0,source:{name:'forged.json',text:JSON.stringify(original)}})).rejects.toThrow(/your accounts/);
    const invalid=structuredClone(original);invalid.rows[1].quantity='broken';await expect(a.store.activity({action:'prepare',accountId:a.account.id,baseRevision:1,source:{name:'bad.json',text:JSON.stringify(invalid)}})).rejects.toThrow(/decimal/);expect((await a.store.activity({action:'read'})).revision).toBe(1);
    const repeated=await a.store.activity({action:'prepare',accountId:a.account.id,baseRevision:1,source:{name:'renamed.json',text:JSON.stringify(original)}});expect(repeated.duplicate).toBe(first.state.events[0].id);
    const overlap=structuredClone(original);overlap.coverage.start='2026-08-01';overlap.reference='Synthetic overlapping statement';
    await page.getByLabel('Activity account',{exact:true}).click();await page.getByRole('option',{name:'Activity validation 1 / Activity test',exact:true}).click();await page.getByLabel('Activity source JSON').setInputFiles({name:'overlap.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(overlap))});await page.getByRole('button',{name:'Preview activity',exact:true}).click();await expect(page.getByRole('button',{name:'Accept activity review'})).toBeDisabled();
    await page.getByLabel('Overlap row-1').click();await page.getByRole('option',{name:/^Duplicate of row-1/}).click();await page.getByLabel('Overlap row-2').click();await page.getByRole('option',{name:'Keep as a separate reported transaction'}).click();await page.getByRole('button',{name:'Update activity review'}).click();await page.getByLabel('I reviewed the account, original source, overlap choices and collection coverage.').check();await page.getByRole('button',{name:'Accept activity review'}).click();await expect(page.getByText('Activity saved at revision 2. Holdings and lot evidence are unchanged.')).toBeVisible();expect(activityView((await a.store.activity({action:'read'})).state).transactions).toHaveLength(3);
    await page.screenshot({path:'test-results/activity-signed-in.png',fullPage:true,animations:'disabled'});
    const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export activity backup'}).click();const download=await downloadPromise,backup=JSON.parse(await readFile(await download.path(),'utf8'));
    // Backup replay uses original decision targets, preserved row IDs and PostgreSQL JSON key order.
    const mapping={[a.account.id]:b.account.id},restore=(await b.store.activity({action:'prepare-restore',baseRevision:0,backup,mapping,reason:'Synthetic backup validation'})).preview;
    const restoreResult=await b.store.activity({action:'accept',preparedId:restore.preparedId,reviewed:true});expect(activityView(restoreResult.saved.state).transactions).toHaveLength(3);expect(restoreResult.saved.audit[0].user_id).toBe(b.user.id);expect(restoreResult.saved.state.events[0].actor).toBe(a.user.id);
    await expect(b.store.activity({action:'prepare-restore',baseRevision:1,backup,mapping,reason:'Occupied destination validation'})).rejects.toThrow(/no existing activity/);
    const request={action:'prepare-withdraw',baseRevision:2,batchId:first.state.events[0].id,reason:'Synthetic source correction'},w1=(await a.store.activity(request)).preview,w2=(await a.store.activity(request)).preview;
    await expect(b.store.activity({action:'accept',preparedId:w1.preparedId,reviewed:true})).rejects.toThrow();await expect(a.store.activity({action:'accept',preparedId:w1.preparedId,reviewed:false})).rejects.toThrow(/Review/);
    const result=await a.store.activity({action:'accept',preparedId:w1.preparedId,reviewed:true});expect((await a.store.activity({action:'accept',preparedId:w1.preparedId,reviewed:true})).receipt).toEqual(result.receipt);await expect(a.store.activity({action:'accept',preparedId:w2.preparedId,reviewed:true})).rejects.toThrow(/stale/);
    const withdrawn=activityView(result.saved.state);expect(withdrawn.transactions).toHaveLength(0);expect(withdrawn.suspended).toHaveLength(1);expect(activityCoverage(result.saved.state,result.saved.accounts,'2026-09-01','2026-09-17')[0].status).toBe('gaps');expect(await a.store.readState()).toEqual(holdings);
    const afterBackup=(await a.store.activity({action:'export'})).backup;const fresh=await good(b.client.from('accounts').insert({user_id:b.user.id,portfolio_id:b.account.portfolio_id,label:'Withdrawal restore',broker:'schwab',account_type:'taxable'}).select().single());
    const restoreContext=await page.context().browser().newContext({baseURL:'http://127.0.0.1:4180'});
    try{
      const restorePage=await restoreContext.newPage();await restorePage.goto('/?workspace=imports');await restorePage.getByRole('textbox',{name:'Email',exact:true}).fill(c.user.email);await restorePage.getByLabel(/^Password/).fill(password);await restorePage.getByRole('button',{name:'Sign in',exact:true}).click();await restorePage.getByRole('button',{name:'Transactions',exact:true}).click();
      await restorePage.getByLabel('Activity backup JSON').setInputFiles({name:'activity-backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(afterBackup))});await restorePage.getByLabel('Activity destination Activity test').click();await restorePage.getByRole('option',{name:'Activity validation 3 / Activity test',exact:true}).click();await restorePage.getByLabel('Activity restore reason').fill('Restore original evidence and withdrawal history');await restorePage.getByRole('button',{name:'Preview activity restore'}).click();await expect(restorePage.getByText('3 historical events will be restored.')).toBeVisible();
      await restorePage.getByLabel('I reviewed the account, original source, overlap choices and collection coverage.').check();await restorePage.getByRole('button',{name:'Accept activity review'}).click();await expect(restorePage.getByText(/0 active records · 1 suspended sources/)).toBeVisible();const restoredWithdrawals=await c.store.activity({action:'read'});expect(restoredWithdrawals.state.events).toHaveLength(3);expect(restoredWithdrawals.state.events[0].source.text).toBe(first.state.events[0].source.text);
    }finally{await restoreContext.close();}
    // Reusing source event IDs in an existing ledger is rejected even with a new account mapping.
    await expect(b.store.activity({action:'prepare-restore',baseRevision:1,backup:afterBackup,mapping:{[a.account.id]:fresh.id},reason:'Duplicate IDs validation'})).rejects.toThrow(/identity|duplicated/);
  }finally{for(const p of people)await p.client.auth.signOut();}
});
