import {test,expect} from '@playwright/test';import {createClient} from '@supabase/supabase-js';import {execFileSync} from 'node:child_process';import {randomUUID} from 'node:crypto';
import {localSupabase} from '../../scripts/configure-local-supabase.mjs';import {supabaseStore} from '../../src/import/supabase-store.ts';import {activityTemplate} from '../../src/activity/engine.mjs';
const good=async p=>{const r=await p;if(r.error)throw Error(r.error.message);return r.data;};
test('alert inbox deduplicates, acknowledges, snoozes, reopens on changed evidence and links the sale review',async({page})=>{
 const config=localSupabase(),raw=JSON.parse(execFileSync('supabase.exe',['status','-o','json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']})),password=`Synthetic-${randomUUID()}-Aa7!`,admin=createClient(config.url,raw.SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
 async function person(){const user=(await good(admin.auth.admin.createUser({email:`alerts-${randomUUID()}@example.test`,password,email_confirm:true}))).user,client=createClient(config.url,config.key,{auth:{persistSession:false,autoRefreshToken:false}});await good(client.auth.signInWithPassword({email:user.email,password}));const portfolio=await good(client.from('portfolios').insert({user_id:user.id,name:'Synthetic alerts'}).select().single()),account=await good(client.from('accounts').insert({user_id:user.id,portfolio_id:portfolio.id,label:'Alert taxable',broker:'schwab',account_type:'taxable'}).select().single());return {user,client,account,store:supabaseStore(client)};}
 const a=await person(),b=await person();
 async function add(action,date){const saved=await a.store.activity({action:'read'}),doc={...activityTemplate(),coverage:{start:'2026-06-01',end:'2026-08-31',status:'complete',noActivity:false},rows:[{...activityTemplate().rows[0],date,action,symbol:'GOOG',rowRef:randomUUID()}]},p=(await a.store.activity({action:'prepare',baseRevision:saved.revision,accountId:a.account.id,source:{name:'synthetic-alert.json',text:JSON.stringify(doc)}})).preview;await a.store.activity({action:'accept',preparedId:p.preparedId,reviewed:true});}
 try{
  await add('sell','2026-07-10');const preferences={opportunities:false,dataQuality:false,tracking:true,minLoss:'100'};await a.store.replacements({action:'alerts-preferences',preferences,revision:0});await a.store.replacements({action:'alerts-scan'});let inbox=await a.store.replacements({action:'alerts-read'});expect(inbox.alerts).toHaveLength(1);const first=inbox.alerts[0];await a.store.replacements({action:'alerts-scan'});expect((await a.store.replacements({action:'alerts-read'})).alerts[0].id).toBe(first.id);
  await expect(b.store.replacements({action:'alerts-action',id:first.id,version:first.version,choice:'acknowledge'})).rejects.toThrow(/unavailable/);expect(await good(b.client.from('alert_inbox').select('*'))).toEqual([]);expect((await a.client.from('alert_inbox').delete().eq('id',first.id)).error).toBeTruthy();
  await page.goto('/?workspace=imports');await page.getByRole('textbox',{name:'Email',exact:true}).fill(a.user.email);await page.getByLabel(/^Password/).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Notifications',exact:true}).click();await expect(page.getByRole('heading',{name:'GOOG: sale review needed'})).toBeVisible();await page.getByLabel('Automatic daily checks',{exact:true}).click();await expect(page.getByText(/Next check due:/)).toBeVisible();expect((await a.store.replacements({action:'alerts-read'})).schedule.enabled).toBe(true);expect(await good(b.client.from('alert_schedules').select('*'))).toEqual([]);expect((await a.client.rpc('claim_alert_schedule')).error).toBeTruthy();await page.getByLabel('Automatic daily checks',{exact:true}).click();await expect(page.getByText(/Next check due:/)).not.toBeVisible();await page.getByRole('button',{name:'Acknowledge',exact:true}).click();await expect(page.getByRole('heading',{name:'GOOG: sale review needed'})).not.toBeVisible();await page.getByRole('button',{name:'Check alerts now',exact:true}).click();await expect(page.getByRole('heading',{name:'GOOG: sale review needed'})).not.toBeVisible();
  await page.getByLabel('Include acknowledged, snoozed and inactive alerts').check();await page.getByRole('button',{name:'Snooze 24 hours',exact:true}).click();await expect(page.getByText(/Snoozed until/)).toBeVisible();
  await add('buy','2026-07-11');await page.getByRole('button',{name:'Check alerts now',exact:true}).click();await expect(page.getByText(/Needs attention · last seen/)).toBeVisible();inbox=await a.store.replacements({action:'alerts-read'});expect(inbox.alerts[0].version).toBeGreaterThan(first.version);expect(inbox.alerts[0].snoozed_until).toBeNull();await expect(a.store.replacements({action:'alerts-action',id:first.id,version:first.version,choice:'acknowledge'})).rejects.toThrow(/changed/);
  await page.screenshot({path:'test-results/alert-inbox.png',fullPage:true});await page.getByRole('button',{name:'Open evidence',exact:true}).click();await expect(page.getByRole('dialog',{name:'Review sale GOOG'})).toBeVisible();
  const sale=inbox.alerts[0].payload.target.saleId,detail=await a.store.replacements({action:'tracking-detail',saleId:sale});await a.store.replacements({action:'tracking-review',saleId:sale,hash:detail.hash,disposition:'closed',note:'Synthetic review complete',reviewed:true});await a.store.replacements({action:'alerts-scan'});expect((await a.store.replacements({action:'alerts-read'})).alerts[0].active).toBe(false);
  await expect(a.store.replacements({action:'alerts-preferences',preferences,revision:0})).rejects.toThrow(/changed/);
  const before=(await a.store.replacements({action:'alerts-read'})).scans.length;const stale=await admin.rpc('commit_alert_scan',{p_user:a.user.id,p_preferences_revision:1,p_holdings:999,p_activity:2,p_alerts:[],p_evaluated:{opportunity:true,data:true,tracking:true}});expect(stale.error).toBeTruthy();expect((await a.store.replacements({action:'alerts-read'})).scans.length).toBe(before);
 }finally{const schedule=await good(admin.from('alert_schedules').select('revision').eq('user_id',a.user.id).maybeSingle());if(schedule)await good(admin.rpc('save_alert_schedule',{p_user:a.user.id,p_revision:schedule.revision,p_enabled:false}));await a.client.auth.signOut();await b.client.auth.signOut();}
});
