import {test,expect} from '@playwright/test';import {createClient} from '@supabase/supabase-js';import {execFileSync} from 'node:child_process';import {randomUUID} from 'node:crypto';import {localSupabase} from '../../scripts/configure-local-supabase.mjs';import {supabaseStore} from '../../src/import/supabase-store.ts';import {sampleFiles} from '../../src/sample.mjs';import {readSource} from '../../src/import/sources.mjs';
const good=async p=>{const r=await p;if(r.error){let message=r.error.message;try{message=(await r.error.context.json()).error||message;}catch{}throw Error(message);}return r.data;};
test('confirmed deletion removes originals and records, isolates another user and supports backup restore',async({page})=>{
 const config=localSupabase(),raw=JSON.parse(execFileSync(process.platform==='win32'?'supabase.exe':'supabase',['status','-o','json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']})),opts={auth:{persistSession:false,autoRefreshToken:false}},admin=createClient(config.url,raw.SERVICE_ROLE_KEY,opts),password=randomUUID()+'Aa7!';
 const make=async()=>{const {user}=await good(admin.auth.admin.createUser({email:`privacy-${randomUUID()}@example.test`,password,email_confirm:true}));const client=createClient(config.url,config.key,opts);await good(client.auth.signInWithPassword({email:user.email,password}));const portfolio=await good(client.from('portfolios').insert({user_id:user.id,name:'Privacy synthetic'}).select().single()),account=await good(client.from('accounts').insert({user_id:user.id,portfolio_id:portfolio.id,label:'Privacy account',broker:'schwab',account_type:'taxable'}).select().single());return {user,client,account,store:supabaseStore(client)};};
 const a=await make(),b=await make();const invoke=(client,body)=>good(client.functions.invoke('imports',{body}));
 try{
 const preview=await a.store.buildPreview({},await Promise.all(sampleFiles().map(readSource)),{accountId:a.account.id,accountLabel:'Privacy account',accountType:'taxable',currency:'USD',sourceAccountRef:'synthetic-account',completeAccount:false});await a.store.commitImport(preview,{symbols:preview.rows.map(r=>r.symbol),includeCash:true,mappingReviewed:true,timingReviewed:true,reason:'Synthetic privacy test'});
 const backup=await a.store.exportBackup(),sources=await good(a.client.from('import_sources').select('path'));
 const deletion=await invoke(a.client,{action:'data-preview'});await expect(invoke(b.client,{action:'data-delete',token:deletion.token,confirmation:'DELETE MY DATA',reviewed:true})).rejects.toThrow();
 await page.goto('/?workspace=accounts');await page.getByRole('textbox',{name:'Email',exact:true}).fill(a.user.email);await page.getByLabel(/^Password/).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Review deletion of all financial data'}).click();const remove=page.getByRole('button',{name:'Permanently delete my financial data'});await expect(remove).toBeDisabled();await page.getByLabel('I have saved the backups I need',{exact:false}).check();await page.getByLabel('Type DELETE MY DATA',{exact:true}).fill('DELETE MY DATA');await page.getByLabel('Confirm password',{exact:true}).fill(password);await remove.click();await expect(page.getByText('Your financial workspace is empty.',{exact:false})).toBeVisible();
 expect(await good(a.client.from('accounts').select('id'))).toEqual([]);expect((await good(b.client.from('accounts').select('id')))).toHaveLength(1);for(const source of sources)expect((await admin.storage.from('import-sources').download(source.path)).error).toBeTruthy();
 await page.getByLabel('Type START EMPTY',{exact:true}).fill('START EMPTY');await page.getByLabel('Confirm password',{exact:true}).fill(password);await Promise.all([page.waitForEvent('load'),page.getByRole('button',{name:'Start empty workspace',exact:true}).click()]);await expect(page.getByRole('textbox',{name:'New portfolio name'})).toBeVisible();
 const portfolio=await good(a.client.from('portfolios').insert({user_id:a.user.id,name:'Restored synthetic'}).select().single()),target=await good(a.client.from('accounts').insert({user_id:a.user.id,portfolio_id:portfolio.id,label:'Restored account',broker:'schwab',account_type:'taxable'}).select().single());const plan=await a.store.prepareRestore(backup,{[a.account.id]:target.id});const restored=await a.store.acceptRestore(plan.preview.preparedId,true);expect(Object.keys(restored.state.holdings[target.id])).toHaveLength(3);
 }catch(e){console.log('Primary synthetic failure:',e.message);throw e;}finally{for(const p of [a,b]){const plan=await invoke(p.client,{action:'data-preview'});await invoke(p.client,{action:'data-delete',token:plan.token,confirmation:'DELETE MY DATA',reviewed:true});await p.client.auth.signOut();await good(admin.auth.admin.deleteUser(p.user.id));}}
});
