import {test,expect} from '@playwright/test';
import {createClient} from '@supabase/supabase-js';import {execFileSync} from 'node:child_process';import {randomUUID} from 'node:crypto';
import {localSupabase} from '../../scripts/configure-local-supabase.mjs';import {supabaseStore} from '../../src/import/supabase-store.ts';import {activityTemplate} from '../../src/activity/engine.mjs';
const good=async p=>{const r=await p;if(r.error)throw Error(r.error.message);return r.data;};
test('imported sales track IRA acquisitions, stale reviews, withdrawal and portable review history',async({page})=>{
 const config=localSupabase(),raw=JSON.parse(execFileSync('supabase.exe',['status','-o','json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']})),password=`Synthetic-${randomUUID()}-Aa7!`,admin=createClient(config.url,raw.SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
 async function person(label){const user=(await good(admin.auth.admin.createUser({email:`sale-${randomUUID()}@example.test`,password,email_confirm:true}))).user,client=createClient(config.url,config.key,{auth:{persistSession:false,autoRefreshToken:false}});await good(client.auth.signInWithPassword({email:user.email,password}));const p=await good(client.from('portfolios').insert({user_id:user.id,name:label}).select().single()),accounts=[];for(const type of ['taxable','roth_ira'])accounts.push(await good(client.from('accounts').insert({user_id:user.id,portfolio_id:p.id,label:type,broker:'schwab',account_type:type}).select().single()));return {user,client,p,accounts,store:supabaseStore(client)};}
 const a=await person('Sale review'),b=await person('Restore review');
 const make=(action,date,symbol='GOOG')=>({...activityTemplate().rows[0],rowRef:randomUUID(),action,date,symbol,quantity:'0.5',cashAmount:action==='sell'?'80':'-80'});
 async function add(account,rows){const saved=await a.store.activity({action:'read'}),doc={...activityTemplate(),coverage:{start:'2026-06-01',end:'2026-10-31',status:'complete',noActivity:false},rows};const p=(await a.store.activity({action:'prepare',baseRevision:saved.revision,accountId:account.id,source:{name:'synthetic.json',text:JSON.stringify(doc)}})).preview;await a.store.activity({action:'accept',preparedId:p.preparedId,reviewed:true});return (await a.store.activity({action:'read'})).state.events.at(-1);}
 try{
  const batch=await add(a.accounts[0],[make('sell','2026-07-10'),make('sell','2026-09-25')]);await add(a.accounts[1],[make('reinvest','2026-07-20','GOOGL')]);
  const before=await a.store.readState(),list=await a.store.replacements({action:'tracking-read'}),sale=list.sales.find(s=>s.date==='2026-07-10'),open=list.sales.find(s=>s.date==='2026-09-25');expect(list.sales).toHaveLength(2);
  const detail=await a.store.replacements({action:'tracking-detail',saleId:sale.id});expect(detail.evidence.acquisitions[0].accountType).toBe('roth_ira');
  await expect(b.store.replacements({action:'tracking-detail',saleId:sale.id})).rejects.toThrow(/your imported/);
  const ongoing=await a.store.replacements({action:'tracking-detail',saleId:open.id});await expect(a.store.replacements({action:'tracking-review',saleId:open.id,hash:ongoing.hash,disposition:'closed',note:'Still open',reviewed:true})).rejects.toThrow(/elapse/);
  await page.goto('/?workspace=imports');await page.getByRole('textbox',{name:'Email',exact:true}).fill(a.user.email);await page.getByLabel(/^Password/).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Results',exact:true}).click();await page.getByRole('button',{name:'Sales & follow-up',exact:true}).click();await expect(page.getByRole('table',{name:'Tracked sales'})).toContainText('GOOG');await page.getByRole('button',{name:`Review sale GOOG ${sale.rowRef}`,exact:true}).click();await expect(page.getByRole('table',{name:'Sale acquisition evidence'})).toContainText('GOOGL');
  await page.getByLabel('Sale review note',{exact:true}).fill('Reviewed IRA evidence; consult tax records.');await page.getByRole('combobox',{name:'Sale review result',exact:true}).click();await page.getByRole('option',{name:'Close review — window elapsed',exact:true}).click();await page.getByLabel('I reviewed the sale, acquisition evidence and gaps; this is not tax clearance.').check();await page.getByRole('button',{name:'Save sale review',exact:true}).click();await expect(page.getByText('Review saved. New evidence or a window milestone will require another review.')).toBeVisible();
  await page.screenshot({path:'test-results/sale-review-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/sale-review-mobile.png'});await page.getByRole('button',{name:'Back to tracking'}).click();await expect(page.getByRole('table',{name:'Tracked sales'})).toContainText('review closed');
  const req={action:'tracking-review',saleId:sale.id,hash:detail.hash,disposition:'closed',note:'Reviewed IRA evidence; consult tax records.',reviewed:true};await a.store.replacements(req);expect((await a.store.replacements({action:'tracking-detail',saleId:sale.id})).reviews).toHaveLength(1);
  await add(a.accounts[1],[make('buy','2026-07-21')]);await expect(a.store.replacements(req)).rejects.toThrow(/changed/);expect((await a.store.replacements({action:'tracking-read'})).sales.find(s=>s.id===sale.id).reviewStatus).toMatch(/changed/);
  const backup=(await a.store.replacements({action:'planning-export'})).backup;expect(backup.data.saleReviews).toHaveLength(1);const mapping={portfolios:{[a.p.id]:b.p.id},accounts:Object.fromEntries(a.accounts.map((x,i)=>[x.id,b.accounts[i].id]))},p=(await b.store.replacements({action:'planning-preview',backup,mapping})).preview;await b.store.replacements({action:'planning-restore',backup,mapping,hash:p.hash,reviewed:true});expect((await b.store.replacements({action:'tracking-read'})).restoredReviews).toBe(1);expect((await b.store.replacements({action:'planning-export'})).backup.data.saleReviews[0].evidence).toEqual(backup.data.saleReviews[0].evidence);
  const saved=await a.store.activity({action:'read'}),withdraw=(await a.store.activity({action:'prepare-withdraw',baseRevision:saved.revision,batchId:batch.id,reason:'Correct source'})).preview;await a.store.activity({action:'accept',preparedId:withdraw.preparedId,reviewed:true});expect((await a.store.replacements({action:'tracking-read'})).sales.every(s=>!s.active)).toBe(true);expect(await a.store.readState()).toEqual(before);
  expect((await a.client.from('sale_reviews').delete().eq('user_id',a.user.id)).error).toBeTruthy();expect((await b.client.from('sale_reviews').select('*').eq('user_id',a.user.id)).data).toEqual([]);
 }finally{await a.client.auth.signOut();await b.client.auth.signOut();}
});
