import {temporaryDailyBatch} from './temporary-market-cache.mjs';
import {test,expect} from '@playwright/test';
import {createClient} from '@supabase/supabase-js';
import {execFileSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {localSupabase} from '../../scripts/configure-local-supabase.mjs';
import {supabaseStore} from '../../src/import/supabase-store.ts';
import {sampleFiles} from '../../src/sample.mjs';
import {readSource} from '../../src/import/sources.mjs';
import {universeTemplate} from '../../src/analysis/replacements.mjs';
const good=async p=>{const r=await p;if(r.error)throw Error(r.error.message);return r.data;};
test('opportunity panel selects fractional lots, saves immutable drafts and preserves filters',async({page})=>{
  const config=localSupabase(),password=`Synthetic-${randomUUID()}-Aa7!`,raw=JSON.parse(execFileSync('supabase.exe',['status','-o','json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));
  const admin=createClient(config.url,raw.SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}),user=(await good(admin.auth.admin.createUser({email:`replacement-${randomUUID()}@example.test`,password,email_confirm:true}))).user;
  const client=createClient(config.url,config.key,{auth:{persistSession:false,autoRefreshToken:false}});await good(client.auth.signInWithPassword({email:user.email,password}));const store=supabaseStore(client);
  let restoreMarket=async()=>{};
  try{
    const portfolio=await good(client.from('portfolios').insert({user_id:user.id,name:'Synthetic replacements'}).select().single());
    const account=await good(client.from('accounts').insert({user_id:user.id,portfolio_id:portfolio.id,label:'Replacement test',broker:'schwab',account_type:'taxable'}).select().single());
    const plan=await store.buildPreview(await store.readState(),await Promise.all(sampleFiles().map(readSource)),{accountId:account.id,currency:'USD',sourceAccountRef:'synthetic-account',completeAccount:false});await store.commitImport(plan,{symbols:plan.rows.map(r=>r.symbol),includeCash:true,mappingReviewed:true,timingReviewed:true,reason:'Synthetic replacement setup'});
    const before=await store.readState(),activity=await store.activity({action:'read'}),document=universeTemplate();document.members.forEach(m=>m.benchmarkWeight=.5);document.validThrough=new Date(Date.now()+86400000).toISOString().slice(0,10);
    const date=new Date(Date.now()-86400000).toISOString().slice(0,10);
    restoreMarket=await temporaryDailyBatch(admin,date,{EXAMPLE:{price:'90',barAt:date+'T20:00:00Z'}});
    const bars=Array.from({length:151},(_,i)=>({date:new Date(Date.UTC(2026,0,1+i)).toISOString().slice(0,10),close:100*Math.exp(i*.001+Math.sin(i)*.01)}));
    for(const symbol of ['EXAMPLE','EXAMPLEB'])for(const kind of ['profile','history'])await good(admin.from('replacement_metric_cache').upsert({symbol,as_of:date,kind,payload:kind==='profile'?{identityVersion:1,industry:'1000',marketCap:1000000}:{bars}}));
    const source={name:'synthetic.json',text:JSON.stringify(document)},up=(await store.replacements({action:'preview',...source})).preview;
    const universe=(await store.replacements({action:'accept',...source,hash:up.hash,reviewed:true})).universe;
    await store.replacements({action:'select',portfolioId:portfolio.id,universeId:universe.id,baseRevision:0,exclusions:[],reviewed:true});
    const inputs=await store.analysis({action:'read'});
    const quote={accountId:account.id,symbol:'EXAMPLE',security:before.holdings[account.id].EXAMPLE.position.security,kind:'provider',provider:'massive',providerSymbol:'EXAMPLE',price:'90',currency:'USD',priceType:'daily-close',priceDate:new Date(Date.now()-86400000).toISOString().slice(0,10),observedAt:null,fetchedAt:new Date().toISOString(),reference:'Synthetic cached close'};
    await page.route('**/functions/v1/get-quotes',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({provider:'Massive',items:[{accountId:account.id,symbol:'EXAMPLE',valid:true,cacheStatus:'daily',quote}]})}));
    await page.goto('/?workspace=imports');await page.getByRole('textbox',{name:'Email',exact:true}).fill(user.email);await page.getByLabel(/^Password/).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:/^Opportunities/}).click();
    await expect(page.getByRole('table',{name:'Holdings with potential losses'})).toContainText('20 USD');await expect(page.getByRole('button',{name:'Complete opportunity setup'})).not.toBeVisible();
    const inline=page.locator('[aria-label="Replacement preview EXAMPLE"]');await expect(inline).toContainText('EXAMPLE → EXAMPLEB');await expect(inline).toContainText('Return-pattern similarity');await page.getByLabel('Opportunity replacement strategy',{exact:true}).click();await page.getByRole('option',{name:'Stay close to index',exact:true}).click();await expect(inline).toContainText('Constituent alignment');
    await page.getByLabel('Find candidate symbol',{exact:true}).fill('EXAMPLE');await page.getByRole('button',{name:'View EXAMPLE lots',exact:true}).click();await page.getByRole('button',{name:'Review trade for EXAMPLE lot 1',exact:true}).click();
    await expect(page.getByRole('region',{name:'Review EXAMPLE'})).toBeVisible();await expect(page.getByLabel('Lot 1 quantity',{exact:true})).toHaveValue('1');
    await page.getByLabel('Lot 1 quantity',{exact:true}).fill('1.1');await expect(page.getByRole('button',{name:'Continue to replacements'})).toBeDisabled();
    await page.getByLabel('Lot 1 quantity',{exact:true}).fill('0.5');await page.getByRole('button',{name:'Continue to replacements'}).click();
    await expect(page.getByLabel('Proposed replacement amount (USD)',{exact:true})).toHaveValue('45');await expect(page.getByLabel('Proposed replacement amount (USD)',{exact:true})).toBeDisabled();
    await page.getByRole('button',{name:'Compare replacements',exact:true}).click();await page.getByRole('button',{name:'Choose EXAMPLEB',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Review your draft'})).toBeVisible();await expect(page.getByRole('button',{name:'Save draft',exact:true})).toBeDisabled();
    await page.getByLabel('I reviewed the selected lots, dated prices and evidence limitations.').check();await page.getByRole('button',{name:'Save draft',exact:true}).click();await expect(page.getByRole('heading',{name:'Draft saved',exact:true})).toBeVisible();
    await page.screenshot({path:'test-results/ux-opportunity-handoff.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/ux-draft-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1100});
    await page.getByRole('button',{name:'Close review',exact:true}).click();await expect(page.getByLabel('Find candidate symbol',{exact:true})).toHaveValue('EXAMPLE');await expect(page.getByRole('table',{name:'Loss candidates'}).getByRole('row')).toHaveCount(3);
    await page.getByRole('button',{name:'Review trade for EXAMPLE lot 1',exact:true}).click();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Review trade for EXAMPLE lot 1',exact:true})).toBeFocused();
    await page.getByRole('button',{name:'Results',exact:true}).click();await page.getByRole('button',{name:'Sales & follow-up',exact:true}).click();await page.getByText('Optional saved trade drafts',{exact:true}).click();await expect(page.getByRole('heading',{name:'Saved trade drafts'})).toBeVisible();await expect(page.getByRole('heading',{name:'EXAMPLE → EXAMPLEB'})).toBeVisible();
    const draft=(await store.replacements({action:'drafts'})).drafts[0],comparison=draft.evidence.comparison,req={comparison,holdingsRevision:draft.evidence.holdingsRevision,lots:[{index:0,quantity:'0.5'}],replacement:'EXAMPLEB'};
    expect((await store.replacements({action:'save-draft',...req,hash:draft.evidence_hash,reviewed:true})).duplicate).toBe(true);
    await expect(store.replacements({action:'save-draft',...req,lots:[{index:0,quantity:'1'}],hash:draft.evidence_hash,reviewed:true})).rejects.toThrow(/changed/);
    const oldPreview=(await store.replacements({action:'preview-draft',...req})).preview;
    await store.replacements({action:'select',portfolioId:portfolio.id,universeId:universe.id,baseRevision:1,exclusions:[],reviewed:true});
    await expect(store.replacements({action:'save-draft',...req,hash:oldPreview.hash,reviewed:true})).rejects.toThrow(/changed/);
    expect((await client.from('trade_drafts').update({evidence:{}}).eq('id',draft.id)).error).toBeTruthy();
    const outsider=(await good(admin.auth.admin.createUser({email:`outsider-${randomUUID()}@example.test`,password,email_confirm:true}))).user;
    const other=createClient(config.url,config.key,{auth:{persistSession:false,autoRefreshToken:false}});await good(other.auth.signInWithPassword({email:outsider.email,password}));expect(await good(other.from('trade_drafts').select('id'))).toEqual([]);expect((await supabaseStore(other).replacements({action:'drafts'})).drafts).toEqual([]);await expect(supabaseStore(other).replacements({action:'preview-draft',...req})).rejects.toThrow(/owned/);await other.auth.signOut();
    expect(await store.readState()).toEqual(before);expect(await store.activity({action:'read'})).toEqual(activity);expect(await store.analysis({action:'read'})).toEqual(inputs);
    await page.reload();await page.getByRole('button',{name:'Results',exact:true}).click();await page.getByRole('button',{name:'Sales & follow-up',exact:true}).click();await page.getByText('Optional saved trade drafts',{exact:true}).click();await expect(page.getByRole('heading',{name:'EXAMPLE → EXAMPLEB'})).toBeVisible();
  }finally{try{await restoreMarket();}finally{await client.auth.signOut();}}
});

